### ISSUE TITLE
Support for xml?

### ISSUE THREAD

**Issue by mgajda** [Wilfred/difftastic#10]
XML documents have structure similar to that of parenthesised languages:
`<block>` is opening parenthesis, `</block>` is the closing one.
Is there any plan to support XML/HTML?

**Comment by Wilfred** [comment]
It's an interesting idea. The extremely simple parser in difftastic using `syntax.toml` wouldn't work well XML's delimiters.

If we used something like roxmltree (an XML parser that preserves comments), we could use difftastic's internal AST and diffing would just work for XML.

I'm going to close this issue for now: it's not a goal before 1.0.

**Comment by DaKnig** [comment]
hi! just wanted to bring your attention to [tree-sitter-xml](https://github.com/dorgnarg/tree-sitter-xml), if that could help. I am also interested in getting xml supported.

**Comment by BerengarWLehr** [comment]
Would love xml support as well

**Comment by DaKnig** [comment]
please add `.ui` files to the xml extension list, thats the extension used by many gnome apps for their xml buildable files

**Comment by Wilfred** [comment]
@DaKnig done :)
