### ISSUE TITLE
plan to expose api

### ISSUE THREAD

**Issue by IWANABETHATGUY** [Wilfred/difftastic#12]
Thanks for the fantastic work!
Is there any plan to expose api to other developer ? so that they could use the api create more diff tool other than only `git diff` 
replacer

**Comment by Wilfred** [comment]
This is definitely I'm interested in future, but it's too early right now. The API is still changing a lot as I figure out how make a design that actually works.

**Comment by luzpaz** [comment]
@Wilfred has there been any progress on your thinking about this ? (sorry for the necrobump)

**Comment by the-moog** [comment]
@luzpaz  I was the person who made the reqeust over at GNOME. https://gitlab.gnome.org/GNOME/meld/-/issues/756

I noticed this [PR](https://github.com/Wilfred/difftastic/pull/231) that adds a library interface, though that has not been looked at for well over a year.  I guess this makes sense as it's not worth publishing an API for a moving target.

Perhaps there is another, simple way to add difft as a backend to meld?
 
There is a feature (experimental) where difftastic emits a simple json file with the `--display <MODE>` option. 
Could that be used with a temp file, named pipe or Bekeley socket until there is a more direct interface?

Example below...

Note this was generated a file with few characters (~15) and a tiny change.  I am wondering if JSON is the best way to communicate that change information? For a large file the diff data could be massive.  There are binary alternatives for arbitrary data serialisation that would be more efficient. e.g. [Apache Thrift](https://en.wikipedia.org/wiki/Apache_Thrift)?  Or maybe do it live with a socket and a virtual cursor - next/prev/print/count etc  that would mean far less data to transfer.

before `(lhs comma rhs)` -> `[(lhs) comma rhs]`  after

``` bash
 DFT_UNSTABLE=yes target/debug/difft \
  --display json \
  sample_files/change_outer_before.el \
  sample_files/change_outer_after.el
```

``` json
{
  "chunks": [
    [
      {
        "lhs": {
          "line_number": 0,
          "changes": [
            { "start": 0, "end": 1, "content": "(", "highlight": "delimiter" },
            { "start": 14, "end": 15, "content": ")", "highlight": "delimiter" }
          ]
        },
        "rhs": {
          "line_number": 0,
          "changes": [
            { "start": 0, "end": 1, "content": "[", "highlight": "delimiter" },
            { "start": 1, "end": 2, "content": "(", "highlight": "delimiter" },
            { "start": 5, "end": 6, "content": ")", "highlight": "delimiter" },
            { "start": 16, "end": 17, "content": "]", "highlight": "delimiter" }
          ]
        }
      }
    ]
  ],
  "language": "Emacs Lisp",
  "path": "sample_files/change_outer_after.el",
  "status": "changed"
}

```
