### ISSUE TITLE
Confusing diff in toml file when un-commenting a line

### ISSUE THREAD

**Issue by sdroege** [Wilfred/difftastic#129]
See screenshot below with the unified diff and difftastic 0.18.1 output

![image](https://user-images.githubusercontent.com/301846/152803398-ee52b929-4e0c-4861-9011-ddd8e72e9733.png)

**Comment by Wilfred** [comment]
I suspect this is the same issue as #122.

**Comment by Wilfred** [comment]
It's tricky to test this without the actual file you're using, but I've fixed a similar bug at least :)

**Comment by sdroege** [comment]
Ah, sorry. I forgot to include that above :) The diff in question is here: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/commit/22ae31bfcb646e6e93c1c8c6407cac52a41d60bd

**Comment by sdroege** [comment]
yes that works correctly now, thanks!
