### ISSUE TITLE
Factoring out code shows part that stayed the same as being removed

### ISSUE THREAD

**Issue by sdroege** [Wilfred/difftastic#134]
Diff in question: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/662

With difftastic 0.19 it looks like the `video_info` is removed from the `State` constructor (there are no further lines below).

![image](https://user-images.githubusercontent.com/301846/152967772-ae10cbb3-a630-4fea-8f0c-79b2d827a4ea.png)

**Comment by Wilfred** [comment]
Yep, there was a bug with no trailing context here. I think the diff is correct now.

![Screenshot from 2022-02-12 12-28-32](https://user-images.githubusercontent.com/70800/153727276-6285b11a-f954-4278-a542-5a0c8a8cbe3b.png)

**Comment by sdroege** [comment]
Yes that looks correct, thanks :)
