### ISSUE TITLE
Generating diff between two large C files takes a long time & uses a lot of memory

### ISSUE THREAD

**Issue by bbannier** [Wilfred/difftastic#153]
Generating a diff between two big C files takes a long time and uses a lot of memory.

```.console
$ difftastic p1.c p2.c
```

In fact I aborted this after ~30min at then 12GB of RAM usage.

`diff` tells me that roughly 8,800 out of 23,000 lines changed here. These are `parser.c` files generated by tree-sitter.

While I wouldn't expect an instantaneous response from `difftastic`, not being able to complete in a couple minutes within reasonable RAM consumption feels off to me. 

Files:
- [p1.c.gz](https://github.com/Wilfred/difftastic/files/8220876/p1.c.gz)
- [p2.c.gz](https://github.com/Wilfred/difftastic/files/8220877/p2.c.gz)

**Comment by Wilfred** [comment]
Could you confirm what version of difftastic you're using? 0.20 has DFT_NODE_LIMIT and DFT_BYTE_LIMIT which should prevent runaway memory usage.

**Comment by Wilfred** [comment]
Hmm, I can reproduce this. It should have hit DFT_BYTE_LIMIT but it doesn't seem to.

**Comment by bbannier** [comment]
> Could you confirm what version of difftastic you're using?

I missed the rename of the binary so `difftastic` in my reproducer above referred to a `0.11.0` installation I still had sitting around.

With 0.21.0 I still see this.

**Comment by Wilfred** [comment]
OK, something in the line-based differ is using an absurd amount of memory in these files. I'm gonna release 0.22 soon, but I'll follow up on this after.

**Comment by Wilfred** [comment]
It looks like the textual diffing is struggling with a file of this size: it's 140,000 lines and the first unchanged line is around line 11,000. The GNU diff docs mention that it strips leading/trailing lines that are unchanged, and difftastic should do this too (for text, it already does this for syntax).

That might not be enough though. There's several LCS diffing libraries on crates.io, but most of them seem unmaintained. I know git has switched diffing algorithms over time, it might be worth looking at its current default algorithm.

**Comment by bbannier** [comment]
Not sure this is just the diffing since I also see e.g., `difft --dump-ts` taking a long time with these files (memory seems to be under control there though). Similarly for `--dump-syntax`. I checked `tree-sitter parse` with the vendored grammar and it seems to return rather quickly.

**Comment by Wilfred** [comment]
Looks like `--dump-ts` was also computing syntax highlighting, which is expensive in files of this size. I've improved this in dba68d1d2ac80db162a051988a10c7f249557ee3, although normal usage still need to compute highlighting.

**Comment by Wilfred** [comment]
OK, performance for this file is now acceptable (3 seconds my machine). There's more optimisations possible, but I'm going to consider this fixed.
