### ISSUE TITLE
More detailed comparisons in wiki with other tools and update README to include Performance

### ISSUE THREAD

**Issue by matu3ba** [Wilfred/difftastic#16]
For example how and if using treesitter works better: https://github.com/afnanenayet/diffsitter

What is your opinion on the project?

"Performance. Difftastic scales poorly on files with a large number of changes. This might be solved by A* search."
It would be nice to add examples like that one from Autochrome
"There are a couple of slow cases, but for the most part I think the gains are worth the switch to Dijkstra. Probably the slowest type of change to diff is splitting a very large form into two or more smaller forms, since we will spend a huge amount of time trying to figure out which smaller form is most similar to the original large form. For example, If you split a 100-line function into two pieces and also make a bunch of changes, it might take like 30 seconds to diff. That's not great, but you'll probably spend more than 30 seconds looking at a diff like that anyway."

**Comment by Wilfred** [comment]
I've discussed tree sitter in #9.

I am regularly expanding the wiki with relevant project as I find them. I'm more interested in building a great tool that cataloguing every single tool out there. There's a ton of line-based diff tools particularly.

Performance is improving and changing, so I don't want to spend too much time documenting the current state. The worst I've seen so far is 8 seconds, where I'd changed almost every line in a 1,000 line file.
