### ISSUE TITLE
Command line argument parsing

### ISSUE THREAD

**Issue by JoelMon** [Wilfred/difftastic#189]
Will you like to use clap to parse command line arguments?  If so, I don't mind taking a crack at it.

**Comment by Wilfred** [comment]
Do you think it's feasible? Difftastic supports being called with 2 arguments (paths), or 7/9 arguments (git). clap seems to push you towards defining subcommands, whereas I need the `difft` to be usable directly from git I think.

**Comment by JoelMon** [comment]
Let me get back to you on that.

**Comment by JoelMon** [comment]
So there's two APIs to build the clap parser.
- The [Builder API ](https://github.com/clap-rs/clap/blob/v3.1.8/examples/tutorial_builder/README.md#positionals)
- The [Derive API](https://github.com/clap-rs/clap/blob/v3.1.8/examples/tutorial_derive/README.md#positionals)

Both API support _positional_ arguments which is how difftastic arguments are written at the moment. Example: `difft file1.rs file2.rs`

**Comment by JoelMon** [comment]
Chris B does a pretty good job at explaining Clap V3: [YouTube](https://www.youtube.com/watch?v=05Buc7gAYzw)

**Comment by Wilfred** [comment]
Difftastic is using clap v3 today. I'm open to PRs that improve how it uses clap, but I can't see any nicer ways of supporting 2, 7 or 9 positional arguments than the current approach.
