### ISSUE TITLE
Expand docs

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#191]
Describe regression tests

Mention rustup in install instructions

**Comment by itissid** [comment]
I have never used rust on my mac, when I installed rust  and cargo using brew and then installed this module I get: 

[RC:[101]]9:15:15: ~/
>> cargo install  diffstatic
    Updating crates.io index
error: could not find `diffstatic` in registry `crates-io` with version `*`

**Comment by Wilfred** [comment]
@itissid you have a typo: "difftastic" not "diffstatic" :)
