### ISSUE TITLE
Add option to force side-by-side view even on single-side changes

### ISSUE THREAD

**Issue by Exagone313** [Wilfred/difftastic#192]
Hi,

Is there an option to force side-by-side view even when there are limited changes that would produce a single-side view?

It seems that the side-by-side view helps viewing some "significant" whitespace changes (which will lead to another issue of mine), but I would like to experiment more with a forced side-by-side view.

Another usage would be to (optionally) keep the view consistent by always displaying two columns.

**Comment by Wilfred** [comment]
Set `DFT_DISPLAY_BOTH=t` when running difftastic.

Display options still need work (I want to expose inline, side-by-side and HTML modes once implemented), but this works fine for the existing side-by-side display.

**Comment by Wilfred** [comment]
0.26 will have a `--display` option, making this more discoverable.
