### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by mdesantis** [Wilfred/difftastic#193]
It would be nice to enable users who don't have / don't want a Rust development environment to download a precompiled binary.

**Comment by atipugin** [comment]
Having pre-built binaries would be super-useful, +1

**Comment by Wilfred** [comment]
@oguzbilgic homebrew is coming, see #201.

**Comment by Wilfred** [comment]
The getting started page in the manual: https://difftastic.wilfred.me.uk/getting_started.html now has a list of packages available for difftastic. Many of these (e.g. Arch Linux) are prebuilt binaries.

Prebuilt binaries is probably nice to have too. We could copy what ripgrep does: https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml -- PRs welcome here.

**Comment by schorsch3000** [comment]
> > Yup.  Or a least give the right instructions on how to compile it.
> 
> `cargo install difftastic` doesn't work for you?

It dosn't work for me:

```
error: unexpected token: `include_str`
   --> /home/heilig/.cargo/registry/src/github.com-1ecc6299db9ec823/textwrap-0.15.0/src/lib.rs:200:9
    |
200 | #[doc = include_str!("../README.md")]
    |         ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `textwrap`.
```

any suggestions?

**Comment by pvonmoradi** [comment]
Meanwhile, if anyone is ok with running mystery binaries from the interwebz, here is `difft (Difftastic 0.25.0)` binary built for Ubuntu 18.04: 
https://transfer.sh/U4KHW5/difft
Here is the sha256 hash so others can verify its integrity:
`fac334aecc614237e39333ef5cd00343340a91813dd6273d4eda0225f4280ea8  difft`

**Comment by littleli** [comment]
> > Yup.  Or a least give the right instructions on how to compile it.
> 
> `cargo install difftastic` doesn't work for you?

I tried on Windows without success.

**Comment by Wilfred** [comment]
OK, GitHub releases are now available.

**Comment by Wilfred** [comment]
@schorsch3000 it looks like your Rust version is older than the minimum required for difftastic (1.56).

**Comment by littleli** [comment]
@Wilfred Don't forget to enable releases on the project sidebar. Enabled by a cog icon next to 'About'. Great job!
