### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by holtwick** [Wilfred/difftastic#194]
This is so awesome! Is there a [Visual Studio Code](https://code.visualstudio.com/docs/editor/extension-marketplace) extension / integration in sight?

**Comment by endigma** [comment]
+1

**Comment by Wilfred** [comment]
I'm not much of a VS Code user myself, so this isn't something I plan to buid. 

I will happily link any extensions in the README or manual, and accept feature requests that make support easier :)

**Comment by theRookieCoder** [comment]
This issue is reliant on something like #73 being resolved. Still, it's a shame I can't use this great tool within VS Code. I'll look into making an extension that just shows the output of the command, as that should be possible currently.

**Comment by holtwick** [comment]
> This is so awesome! Is there a [Visual Studio Code](https://code.visualstudio.com/docs/editor/extension-marketplace) extension / integration in sight?

This project was brought to my attention, which offers similar features and a VSCode integration: https://semanticdiff.com/

**Comment by theRookieCoder** [comment]
I've heard of that extension before, however the languages it supports are pretty limited (doesn't support Rust afaik).
