### ISSUE TITLE
Add Nix support

### ISSUE THREAD

**Issue by otavio** [Wilfred/difftastic#196]
Please consider adding support to [Nix](https://github.com/cstrahan/tree-sitter-nix); I am a NixOS user and it'd be nice to have it fully supported.

**Comment by ncfavier** [comment]
Would love to see this as well!

**Comment by mjlshen** [comment]
I looks like it's already there: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/text/difftastic/default.nix

**Comment by ncfavier** [comment]
That's difftastic in nixpkgs, not nix in difftastic :)
