### ISSUE TITLE
[feature] add an option to specify language

### ISSUE THREAD

**Issue by setop** [Wilfred/difftastic#199]
I have a usecase where I don't pass arguments as filename with extension - `difft --dump-ts <(echo 'a = (1,2)')`. I get `No tree-sitter parser for file: "/dev/fd/63"` as the "file" has no extension. But I know this is python syntax.

I imagine there are other cases where the language is not given by an extension (like sometine we dont pu ".sh" for a shell script).

Would it be possible to explicitly give the language with an option flag ?

**Comment by Wilfred** [comment]
Related: #52.

**Comment by luckman212** [comment]
awesome! 🚀
