### ISSUE TITLE
Missing build instructions & requirement listing

### ISSUE THREAD

**Issue by eyalroz** [Wilfred/difftastic#202]
I'm not a Rust specialist. The repository should tell me (probably in the README.md):

1. What I need installed to build difftastic.
2. What commands I should issue in order to build.

**Comment by paxsali** [comment]
See:
https://difftastic.wilfred.me.uk/getting_started.html

`cargo install difftastic`

But I agree it should be on the main README.md as well.

Also binary releases would make sense for ppl with older rust & cargo version in their OS's package repos.
