### ISSUE TITLE
Detect resized terminal

### ISSUE THREAD

**Issue by durka** [Wilfred/difftastic#209]
difft --version = 0.24.0, Ubuntu 18.04

difftastic does not reformat itself (i.e. change the column width) when the terminal is resized. Is it possible to do this?

**Comment by Wilfred** [comment]
This isn't possible with the default side-by-side display, because difftastic needs to calculate the terminal width to decide how wide to make each column. The inline display doesn't suffer this problem though (`INLINE=y` on 0.25, `--display=inline` on 0.26).

**Comment by Wilfred** [comment]
I think this is an inherent limitation of a tool that writes to stdout without a pager I'm afraid. I'd eventually like to support HTML output, which will have this flexibility, but I don't see any options here.
