### ISSUE TITLE
Panic when lhs and rhs are different and a unicode character appears at the end

### ISSUE THREAD

**Issue by blurgyy** [Wilfred/difftastic#217]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

Diffing on the following two contents cause difft to panic:

```text
1
🟩
```

and

```text
2
🟩
```

It seems that difft tries to slice the last unicode character `🟩` from within its boundary:

```log
thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside '🟩' (bytes 0..4) of `🟩`', src/style.rs:48:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

See above.

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

```shell
$ /bin/difft --version
Difftastic 0.24.0
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
$ uname -rm
5.17.1-zen1-1-zen x86_64
```

**Comment by liyiheng** [comment]
Same here， panicked at Chinese characters
