### ISSUE TITLE
Please add support for Kotlin

### ISSUE THREAD

**Issue by krzema12** [Wilfred/difftastic#220]
Pretty self-explanatory :)

On the list of supported languages I see some that I don't recognize, while Kotlin is first-class citizen in Android development and getting more and more popular on the server side. If Java and Scala are supported, Kotlin would be a natural choice :)

**Comment by Wilfred** [comment]
Done.

I'm interested in supporting all mainstream languages, assuming a tree-sitter parser is available. No promises about what order I add languages though :)
