### ISSUE TITLE
DFT_BACKGROUND=light has no impact on output of difft

### ISSUE THREAD

**Issue by hardyoyo** [Wilfred/difftastic#224]
(1) Description of bug:

I use a light-colored background for my terminal. In difft's output, the filenames are in yellow text, which is unreadable on a light-colored background. Difft's help/usage command indicates that the DFT_BACKGROUND environment variable will alter this behavior, when set to 'light'. This does not appear to be the case.

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

Not necessary, but I'm trying to use difft as my git diff tool.

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

* Difftastic 0.25.0
* Mac OSX (Monterey 12.3.1)

**Comment by hardyoyo** [comment]
This is the culprit here, I think:

https://github.com/Wilfred/difftastic/blob/master/src/style.rs#L320-L325

Yellow is just the wrong choice for a light background.

**Comment by Wilfred** [comment]
This is consistent with how git displays changes. How bad is it on your theme with yellow?

**Comment by Wilfred** [comment]
Given this is consistent with other diff tools, I think the current behaviour is reasonable. ANSI colours is a very limited palette and terminal emulators generally choose visible colours appropriate for the theme.
