### ISSUE TITLE
Add support for Swift programming language

### ISSUE THREAD

**Issue by ccjensen** [Wilfred/difftastic#233]
Thanks for a great tool!

I'd love to see support for the [Swift](https://www.swift.org/) programming language.

**Comment by ccjensen** [comment]
oh, just noticed this PR which means it's likely already in-progress?
https://github.com/Wilfred/difftastic/pull/225

**Comment by Xuanwo** [comment]
#225 has been merged.

Although we have issues like https://github.com/Wilfred/difftastic/issues/277 unsolved, I think it's OK to close this issue now.

ping @Wilfred for action.

**Comment by Wilfred** [comment]
Agreed, the basic functionality is present now :)
