### ISSUE TITLE
Slow diffing of fs/io_uring.c in Linux

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#236]
Compare v5.16..v5.17 -- shows a bunch of syntax errors too.

**Comment by Wilfred** [comment]
https://github.com/torvalds/linux/blob/v5.17/fs/io_uring.c
https://github.com/torvalds/linux/blob/v5.16/fs/io_uring.c

**Comment by Wilfred** [comment]
Looks like a few cases weren't split up well, leading to nodes with >2000 children being diffed.

Logging would really benefit from time information, and maybe treating larger node counts as a warning to keep these cases less overwhelming. It'd be nice to show the position of the first node too, to see which node it's finding.

Note also there are a ton of parsing errors, looks like tree-sitter doesn't like `__foo` in Linux.

**Comment by Wilfred** [comment]
The particularly slow nodes:

```
 WARN  difft::dijkstra > LHS nodes: 646 (10 toplevel), RHS nodes: 657 (10 toplevel)
 WARN  difft::dijkstra > Time: 41.266267ms
 WARN  difft::dijkstra > LHS nodes: 631 (2 toplevel), RHS nodes: 1122 (5 toplevel)
 WARN  difft::dijkstra > Time: 1.244630738s
 WARN  difft::dijkstra > LHS nodes: 4000 (2 toplevel), RHS nodes: 3945 (2 toplevel)
 WARN  difft::dijkstra > Time: 2.749917189s
 WARN  difft::dijkstra > LHS nodes: 1565 (13 toplevel), RHS nodes: 0 (0 toplevel)
 WARN  difft::dijkstra > Time: 1.716246ms
 WARN  difft::dijkstra > LHS nodes: 1171 (14 toplevel), RHS nodes: 2495 (20 toplevel)
 WARN  difft::dijkstra > Time: 6.766049464s
 WARN  difft::dijkstra > LHS nodes: 1098 (7 toplevel), RHS nodes: 815 (4 toplevel)
 WARN  difft::dijkstra > Time: 1.096524547s
 WARN  difft::dijkstra > LHS nodes: 775 (2 toplevel), RHS nodes: 795 (2 toplevel)
 WARN  difft::dijkstra > Time: 23.880298ms
 WARN  difft::dijkstra > LHS nodes: 553 (2 toplevel), RHS nodes: 583 (2 toplevel)
 WARN  difft::dijkstra > Time: 28.838997ms
 WARN  difft::dijkstra > LHS nodes: 537 (4 toplevel), RHS nodes: 529 (4 toplevel)
 WARN  difft::dijkstra > Time: 26.442225ms
```

**Comment by Wilfred** [comment]
The slowest region is the novel section starting at RHS `io_init_poll_iocb`. The LHS function `__io_arm_poll_handler` has been split between several RHS functions. This is particularly unfortunate given that RHS has a function called `__io_arm_poll_handler` too.

**Comment by Wilfred** [comment]
It might be worth setting a baseline diff of everything being novel, and giving up if the cost exceeds 90% of the worst case. There would need to be a minimum number of nodes to do this on, as small trees can be optimally diffed. Optimal diffs are still sometimes confusing though.

**Comment by quackenbush** [comment]
Adding a comment here, as I ran into a hang while diffing completely orthogonal files with difft (ie files have no similarities).

I'm not familiar with your diff algorithm, but it seems to grow exponentially as differences get larger.

```
head -10000 /usr/share/dict/words > words1
tail -10000 /usr/share/dict/words > words2
```

In this example, gnu diff is ~75x faster than difft:

```
> time difft words1 words2
real    0m6.763s

> time diff words1 words2
real    0m0.090s
```

**Comment by Wilfred** [comment]
@quackenbush thanks for the report! That looks like an issue with plaintext diffing performance rather than syntactic diffing, but I've made that case way faster in 0e3c57c64a09acc029d44ee72c559f278c4befa8 :)

**Comment by quackenbush** [comment]
Thanks for the quick update @Wilfred .  I'll check out the next release.

**Comment by quackenbush** [comment]
I just compiled and ran the new version.

```
> time target/release/difft words1 words2

real    0m0.069s
```

Much faster indeed.
