### ISSUE TITLE
Automate releases with JReleaser

### ISSUE THREAD

**Issue by aalmiray** [Wilfred/difftastic#237]
https://jreleaser.org/ may be used to package and distribute Rust binaries to different channels: such as Git releases, Homebrew, macports, Scoop, Snapcraft, etc.

Here are two projects showcasing sample configuration:

https://github.com/manojkarthick/czen
https://github.com/aalmiray/helloworld-rustx

**Comment by Wilfred** [comment]
Thanks, I'll consider it when I set up releases :)
