### ISSUE TITLE
Wrong indentation with tabs

### ISSUE THREAD

**Issue by chrismwendt** [Wilfred/difftastic#24]
To repro:

- Clone https://github.com/gorilla/mux
- Run

```
CLICOLOR_FORCE=1 GIT_EXTERNAL_DIFF=difftastic git log -p --ext-diff 98cb6bf42e086f6af920b965c38cacc07402d51b
```

Result:

![CleanShot 2021-07-25 at 15 10 33](https://user-images.githubusercontent.com/1387653/126912080-9a7b2422-c800-45de-8fa3-6ff3396fd3f6.png)

**Comment by Wilfred** [comment]
Thanks for the report! I'll take a look.

(I've been thinking that difftastic should work pretty well for Go too.)
