### ISSUE TITLE
[Feature Request] Integration with Git

### ISSUE THREAD

**Issue by JoaoGFarias** [Wilfred/difftastic#240]
One of great down-points of Git diff is its programming language ignorance,
making some of the diff output difficult to understand from a programming POV.

Since both difftastic and Git used mainly for programming, it would be great to
run `git diff` using difftastic engine.

Is it possible/makes sense?

**Comment by schorsch3000** [comment]
Read the docs!
Have you seen https://difftastic.wilfred.me.uk/git.html ?

**Comment by Wilfred** [comment]
Yep, this is already supported, see the manual :) https://difftastic.wilfred.me.uk/git.html
