### ISSUE TITLE
Panic on `unreachable!()` code with `.tsx` files

### ISSUE THREAD

**Issue by marcospb19** [Wilfred/difftastic#246]
# Problem
I ran
```sh
difft a.tsx b.tsx
```
Then
```                                                                                              
thread 'main' panicked at 'internal error: entered unreachable code: Should be impossible: every LHS Unchanged MatchedPos should have a corresponding RHS Unchanged MatchedPos', src/hunks.rs:493:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Files
you can get both `a.tsx` and `b.tsx` via [this gist](https://gist.github.com/marcospb19/18e80f72d0a899305e520cfc8384aa02)

This originally was triggered by running:

```
GIT_EXTERNAL_DIFF=difft git diff HEAD~1
```

Then I found the specific file that was making it panic, got the HEAD~1 and HEAD versions, and removed most of the code that didn't caused the error, the original files were larger.

HEAD was just a lint/format commit, so the files are almost equal, the formatter just break some lines considering the line limit.

# Version
Compiled from source, version 0.26 at commit 1c416733ef94c29191a767745c70c444572b54c1.

**Comment by Wilfred** [comment]
Minimal repro:

Before:

```
const AttachmentInput = (
    <div>
          Adicionar arquivos{" "}
    </div>
  );
```

After:

```
const AttachmentInput = (
    <div>
          Adicionar arquivos
          {" "}
    </div>
  );
```

**Comment by Wilfred** [comment]
I think it's crashing from the string contents of the `div` crossing different numbers of lines on LHS and RHS.
