### ISSUE TITLE
Feature request: Perl support

### ISSUE THREAD

**Issue by brneor** [Wilfred/difftastic#250]
First, thank you for this amazing tool.

It would be great to have Perl support even though it's not a very popular language anymore.

**Comment by Xuanwo** [comment]
We need Perl's binding of tree-sitter.

**Comment by Xuanwo** [comment]
I'm working on this now.

**Comment by Xuanwo** [comment]
Perl support has been added in #263. Welcome for testing and leaving review comments :rocket:

**Comment by brneor** [comment]
@Xuanwo ty so much, I'll try it asap :)
