### ISSUE TITLE
Hard to distinguish syntax highlighting from diff

### ISSUE THREAD

**Issue by Hocuri** [Wilfred/difftastic#265]
I often get diffs like this:

![Screenshot_2022-04-22_21-07-38](https://user-images.githubusercontent.com/18012815/164778595-45c3097d-3c1a-4173-8bc1-032dc01ed8c9.png)

where it takes me quite some time to see what actually changed because the syntax highlighting is just as colorful and eye-catching as the actual diff.

Two possible solutions:
- Add an option to turn off the syntax highlighting (I actually never wished I had syntax highlighting with the normal `git diff`, while I often wished I had a diff understanding the syntax)
- Highlight the diff more, e.g. by using red/green background for the diff (that's what GitHub does)

Thank you for this great tool!

**Comment by Wilfred** [comment]
I've opened #275 to track fancier colours, but I agree disabling syntax highlighting is a reasonable feature too.

**Comment by AndrewKvalheim** [comment]
I find that a nice balance is to keep syntax highlighting on but apply dim (SGR 2) to the unchanged text. Then you can even use syntax highlighting on the changes and without dim they’ll visually stand out.
