### ISSUE TITLE
Add Julia support

### ISSUE THREAD

**Issue by matbesancon** [Wilfred/difftastic#284]
A julia highlight could be added with the following parser, used by formatters and IDEs:
https://github.com/julia-vscode/CSTParser.jl

**Comment by Wilfred** [comment]
It should be possible to add Julia support, but difftastic needs a tree-sitter parser.

**Comment by Xuanwo** [comment]
I'm interested in adding Julia support.

As we have https://github.com/tree-sitter/tree-sitter-julia, it should be simple :rocket:

**Comment by matbesancon** [comment]
thanks!
