### ISSUE TITLE
0.6.0: missing colors when default git pager is used

### ISSUE THREAD

**Issue by vlsi** [Wilfred/difftastic#29]
`.gitconfig`:

```
[pager]
        difftool = true
```

It makes `git difftool` output paged, however, the color is not there :-/
`CLICOLOR_FORCE=1 git difftool` results in colored output, however, it looks like the coloring should be detected automatically.

Do you think `difftastic` could detect if the pager is color-enabled automatically?

**Comment by Wilfred** [comment]
Yeah, I don't like that `CLICOLOR_FORCE=1` is necessary in a bunch of places. I'm not sure why it's happening yet, but it's definitely a bug.

**Comment by vlsi** [comment]
@Wilfred , I just configured `difftastic` on a new machine, and I realized the pager is not enabled by default.

WDYT of adding the following to https://difftastic.wilfred.me.uk/git.html#git-difftool ?

```ini
[pager]
        difftool = true
```
