### ISSUE TITLE
Performance issue with the redundancy operations

### ISSUE THREAD

**Issue by yyzdtccjdtc** [Wilfred/difftastic#293]
https://github.com/Wilfred/difftastic/blob/f028b460037cd767adab832306cccfd3c4890705/src/display/hunks.rs#L579-L580

The struct LineNumber store a usize which is 8 byte. But under normal circumstances, it is very unlikely that a file will have more than 2^32 (4,294,967,295) lines of code. If we replace LineNumber with u32, we can reduce the redundant loading of 0's of the 4 high bytes then improve performance.

According to my tests, if we replace all the LineNumber within hunks.rs file with u32, the average execution time decreased from 4.2s to 3.8s, which is a 10% speedup.

Hope this information helps!

**Comment by Wilfred** [comment]
Agreed, this seems like a worthwhile change.

Which files did you benchmark on? The diffing logic usually takes the majority of the time.

**Comment by Wilfred** [comment]
I tried this: https://github.com/Wilfred/difftastic/commit/23f6a9f5c7cb904a23b8e3629ba7df4a3a62afbf and I only saw a ~0.3% improvement, measuring on elisp_before.el, load_before.js and Session_before.kt.

Would love a PR if you're doing something different :)

**Comment by yyzdtccjdtc** [comment]
Thanks for your reply! These are the two cpp files I used for the benchmarking(Since github wouldn't let me upload .cpp format, I switched them to txt format.). I'll try to create a PR later for you to test.
[test2.txt](https://github.com/Wilfred/difftastic/files/8791612/test2.txt)
[test.txt](https://github.com/Wilfred/difftastic/files/8791611/test.txt)

**Comment by Wilfred** [comment]
FWIW I also noticed that column numbers could be u32.
