### ISSUE TITLE
git diff output change, but using difftastic report No syntactic changes.

### ISSUE THREAD

**Issue by fatelei** [Wilfred/difftastic#294]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.
`git config`

<img width="572" alt="image" src="https://user-images.githubusercontent.com/961094/170833355-517aa353-de78-45c7-bd14-13132d9c6038.png">

`git status`
<img width="625" alt="image" src="https://user-images.githubusercontent.com/961094/170833388-0960a290-5988-4685-9cbf-687dda7cd80f.png">

`git difftool`
<img width="451" alt="image" src="https://user-images.githubusercontent.com/961094/170833398-71903832-97ea-4869-ad8c-ad9fd03c0d00.png">

`git diff`
<img width="451" alt="image" src="https://user-images.githubusercontent.com/961094/170833408-c14c01b7-6298-4b28-ae1e-3f2e8f4cfb30.png">

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

https://github.com/fatelei/dbpack/commit/c3de45576f1fd8cc3f3025aba74aa959d0577b13

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

- Difftastic 0.28.0
- OS: macos

**Comment by Wilfred** [comment]
Difftastic is doing the right thing here: only whitespace changed in the commit. What were you expecting?

**Comment by fatelei** [comment]
i check the doc, i misunderstand it

**Comment by Mo0rBy** [comment]
I cam across this and I was wondering if there was some sort of config option that allows you to see the diff, even when there are no syntactic changes.

I have some automated formatting things and I would just like to double check that they have formatted things in the way that I expect.
