### ISSUE TITLE
`git log` and `git show` fail on Windows with "No such file: /dev/null"

### ISSUE THREAD

**Issue by cgranade** [Wilfred/difftastic#296]
When using `git show <commit-id> --ext-diff` on Windows for commits that include creating a new file, an error is raised by `difft` indicating that it was called with `/dev/null` as an argument, despite that no such file exists on Windows:

```
git show HEAD --ext-diff
commit a77b7f947a73da887d2cc7692b17372d115a7961 (HEAD -> main, origin/main, origin/HEAD)
Author: ...
Date:   ...

No such file: /dev/null
fatal: external diff died, stopping at ...
```

- Difftastic 0.28.0
- Windows 11 22610.1

**Comment by Wilfred** [comment]
Interesting, thanks. I'm guessing that git calls the diff tool with `/dev/null` for new files, regardless of whether it's on a platform that has `/dev/null` as a valid path.

**Comment by nzbart** [comment]
@Wilfred I'm still experiencing this in `Difftastic 0.37.0`.

**Comment by OndrejNepozitek** [comment]
Also happens to me, Windows 10, Difftastic 0.41.0. Unfortunately, this makes it impossible to use difftastic with git on Windows.

**Comment by Wilfred** [comment]
@OndrejNepozitek could you try setting `RUST_LOG=info` and running git again?

This should show what arguments difftastic is getting, e.g.

```
2023-01-15T23:13:10.838Z INFO  difft::options > CLI arguments: ["src/display/hunks.rs", "/tmp/git-blob-Lb98A6/hunks.rs", "08e25505d8b9373c6265a99a5b775e2dc4f4bf6c", "100644",
```

This should hopefully show the `/dev/null` string somewhere, but I'm guessing it's slightly different on Windows.

**Comment by n9v9** [comment]
Hi, I found this issue yesterday and decided to try and fix it.

Example to reproduce this issue:

```
mkdir repo
cd repo
git init
git config diff.external difft
copy nul foo.txt
git add foo.txt
git diff --staged
```

Enable `RUST_LOG`:

```
set RUST_LOG=info
```

Output of `git diff`:

```
2023-02-01T16:26:03.783Z INFO  difft::options > CLI arguments: ["foo.txt", "/dev/null", ".", ".", "foo.txt", "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391", "100644"]
No such file: /dev/null
fatal: external diff died, stopping at foo.txt
```

If committing this change and then deleting the file with:

```
git commit -m Initial
del foo.txt
```

and then running `git diff` again, we get the following output:

```
2023-02-01T16:30:02.797Z INFO  difft::options > CLI arguments: ["foo.txt", "C:\\Users\\TESTUS~1\\AppData\\Local\\Temp/git-blob-a06828/foo.txt", "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391", "100644", "/dev/null", ".", "."]
No such file: /dev/null
fatal: external diff died, stopping at foo.txt
```

The behavior of `/dev/null` is documented [here](https://git-scm.com/docs/git#Documentation/git.txt-codeGITEXTERNALDIFFcode):

> The file parameters can point at the user’s working file (e.g. new-file in "git-diff-files"), /dev/null (e.g. old-file when a new file is added), or a temporary file (e.g. old-file in the index).

I got it working on my machine, just have to prepare a pull request :)
