### ISSUE TITLE
[FEATURE] Distribute releases on Chocolatey

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Wilfred/difftastic#299]
[Chocolatey is a package manager for Windows](https://chocolatey.org/). You could set it up on this repository using [this github action](https://github.com/marketplace/actions/chocolatey-action). This would make it a lot easier to keep difftastic updated on Windows

**Comment by Wilfred** [comment]
I don't want to handle packaging for difftastic I'm afraid. Feel free to package difftastic there if it suits you :)

**Comment by ItsIgnacioPortal** [comment]
Alright, so there's two options:

1) I create a repository that uses GitHub actions to periodically check for new releases in this repository, and handle everything necessary to automatically push to chocolatey. You wouldn't need to do anything, but this GitHub action would trigger on a set timer, and it could cause a delay of several weeks between GitHub releases and chocolatey releases. It would also omit some releases if they were released within the same waiting time frame.

2) I create a repository that waits for a Repository Dispatch event. Your repository uses GitHub actions to send said event, which causes my repo to do everything necessary to automatically push to chocolatey. The only downside is that you'd have to create a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with the `public_repo` scope, add it to this repository's [Encrypted Secrets storage](https://docs.github.com/en/actions/security-guides/encrypted-secrets) (so only you have access to it), and then accept a pull request of mine. But there would be no delay between releases, and no skipped releases.

Do you think you could do the second? I can automate everything else :)
