### ISSUE TITLE
YAML problem with large pnpm-lock.yaml

### ISSUE THREAD

**Issue by frontsideair** [Wilfred/difftastic#306]
I'm using difftastic as my git diff tool and I'm frequently diffing `pnpm-lock.yaml` files, which are lockfiles of [pnpm](https://pnpm.io) package manager. If I'm diffing the whole index, difftastic hangs when I scroll to `pnpm-lock.yaml` file. If I'm diffing the `pnpm-lock.yaml` directly, it doesn't show any output. In either case, I have to exit with `Ctrl-C` and `q`.

I tried to reproduce it cleanly using a few packages, but it worked fine. I'm guessing it hangs with large lockfiles. Here's a reproduction: https://gist.github.com/frontsideair/b9ce75e07c7c75c7365e7b47aff4e68d

I'm using version "0.29.1" on macOS aarch64.

**Comment by Wilfred** [comment]
Thanks for the repro.

It's taking 13 seconds and 9GiB on my machine. Difftastic should probably fall back to line-based diffing more aggressively, as this is too slow.

**Comment by frontsideair** [comment]
On my M1 Pro machine:

v0.29.1: 8.51s user 30.34s system 67% cpu 57.428 total
v0.30.0: 1.84s user 5.85s system 71% cpu 10.721 total

Definitely an improvement but still a bit slow unfortunately.

**Comment by Wilfred** [comment]
This file is now vastly faster (0.12 seconds on my machine) as of the above commit :)

**Comment by frontsideair** [comment]
Awesome, I'l give it a try soon!

**Comment by frontsideair** [comment]
I forgot about this but on v0.32.0 it takes 0.07 seconds, which is pretty awesome!
