### ISSUE TITLE
No way to ignore variable renames

### ISSUE THREAD

**Issue by jyn514** [Wilfred/difftastic#313]
Hello! This is a super cool tool, but it doesn't quite do what I want. I recently made a change renaming a variable used in ~300 different places, and I'd like to show everything *except* the rename itself. I tried running `difft` on the change, but it shows the rename and doesn't seem to have an option to disable that. Is there a way to do this?

![image](https://user-images.githubusercontent.com/23638587/177589452-f10b3fda-746a-4223-b600-efbbad2a7a4a.png)

https://github.com/rust-lang/rust/pull/98975/commits/6a8cf2dcd5a0cf1284bf68fdf8e558aef3fc590d

```
$ difft --version
Difftastic 0.30.0
$ uname -a
Linux pop-os 5.17.5-76051705-generic #202204271406~1653440576~20.04~6277a18-Ubuntu SMP PREEMPT Thu Ma x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Wilfred** [comment]
I don't really understand what you're asking here. Difftastic shows what's changed, and as you mention the method name has changed.

What would you expect in this case? How would you characterise the subset of changes that you want to see?

**Comment by jyn514** [comment]
I would like an option to either:
a) collapse all these changes into one (maybe showing only the change in the struct definition?), or
b) ignore all changes from `debugging_opts` to `unstable_opts`

This is the subset of changes I'd like to see:
```diff
diff --git a/compiler/rustc_session/src/config.rs b/compiler/rustc_session/src/config.rs
index e7717f1367c..9f17fbaede1 100644
--- a/compiler/rustc_session/src/config.rs
+++ b/compiler/rustc_session/src/config.rs
@@ -781,7 +781,7 @@ pub fn get_symbol_mangling_version(&self) -> SymbolManglingVersion {
     }
 }
 
-impl DebuggingOptions {
+impl UnstableOptions {
     pub fn diagnostic_handler_flags(&self, can_emit_warnings: bool) -> HandlerFlags {
         HandlerFlags {
             can_emit_warnings,
@@ -1402,6 +1402,7 @@ pub fn rustc_short_optgroups() -> Vec<RustcOptGroup> {
 /// long-term interface for rustc.
 pub fn rustc_optgroups() -> Vec<RustcOptGroup> {
     let mut opts = rustc_short_optgroups();
+    // FIXME: none of these descriptions are actually used
     opts.extend(vec![
         opt::multi_s(
             "",
@@ -1410,7 +1411,7 @@ pub fn rustc_optgroups() -> Vec<RustcOptGroup> {
             "NAME[=PATH]",
         ),
         opt::opt_s("", "sysroot", "Override the system root", "PATH"),
-        opt::multi("Z", "", "Set internal debugging options", "FLAG"),
+        opt::multi("Z", "", "Set unstable / perma-unstable options", "FLAG"),
         opt::opt_s(
             "",
             "error-format",
@@ -1652,12 +1653,12 @@ pub fn parse_crate_edition(matches: &getopts::Matches) -> Edition {
     edition
 }
 
-fn check_debug_option_stability(
+fn check_error_format_stability(
```

None of those are a syntactic change from `debugging_opts` to `unstable_opts`, and it's easy to miss them because the rest of the commit is so large.

**Comment by jhpratt** [comment]
It feels like this would need to integrate a chunk of the compiler to do this, as how else would you know if a name change is to the same type?

**Comment by Wilfred** [comment]
I'm afraid this is out of scope for difftastic: it's not capable of doing this.

Difftastic parses code to a tree-sitter AST, converts that to a simple s-expression representation (everything is a list or an atom), and then performs a structural diff. The structural diff has no notion of specific syntactic positions, and doesn't even have a notion of a rename (every s-expression is either added, removed or unchanged).
