### ISSUE TITLE
Syntax highlight in the diff output

### ISSUE THREAD

**Issue by vlsi** [Wilfred/difftastic#32]
It would be nice if there was syntax highlighting in the diff output, so the code structure is easier to understand.

Sample PL/SQL diff:

git version 2.33.0
<img width="1057" alt="diff with git 2.33" src="https://user-images.githubusercontent.com/213894/132167666-c92a0f44-a692-40e3-9c3b-b7a3a4c48d84.png">

difftastic 0.8
<img width="1413" alt="diff with difftastic 0.8" src="https://user-images.githubusercontent.com/213894/132167697-b93cfde1-e2ce-4c5e-b9b9-c55e4e220433.png">

delta 0.8.3
<img width="1123" alt="diff with delta 0.8.3" src="https://user-images.githubusercontent.com/213894/132167724-41acc709-910c-4a46-8b3a-4303bbd41c56.png">

---

PL/SQL diff where the diff is within string literals (the indentation at line 256 looks odd, and I did not notice it before I took the screenshots).
The code is "PL/SQL code generator written in PL/SQL", and I do not expect that PL/SQL code within string literals to be highlighted as PL/SQL :) However, it would be nice if string literals were highlighted differently from the regular code.

git version 2.33.0
<img width="1010" alt="git version 2.33.0" src="https://user-images.githubusercontent.com/213894/132168336-1087393c-a9b5-426e-94fc-a93d9a0ef54f.png">

difftastic 0.8
<img width="1410" alt="difftastic 0.8" src="https://user-images.githubusercontent.com/213894/132168354-992084f2-fdec-48c2-b1ef-a36eda8e19dc.png">

delta 0.8.3
<img width="1073" alt="delta 0.8.3" src="https://user-images.githubusercontent.com/213894/132168368-ac2a848f-571a-46ae-8ea0-94e6e1e232b2.png">

---

Re "string literals vs code" there's a semi-standard extension from IntelliJ: https://www.jetbrains.com/help/idea/using-language-injections.html#use-language-injection-comments

For instance, the following bit in Groovy code (Jenkins Job DSL code) is highlighted as XML in IntelliJ IDEA:

```
// $/ ... /$ is a multi-line string in Groovy
//  language=xml comment triggers "inject XML into the following literal" in IDEA
+ echo('> config/config.xml', /* language=xml */ $/
<root>
  <profile>
    <datasources>
    </datasources>
  </profile>
</root>
/$) +
```

**Comment by Wilfred** [comment]
Yeah, I think syntax highlighting would be very worthwhile. It's not something I plan to work on until I've got the diffing logic solid, so it's not a high priority for me.

For your specific example, I'm afraid difftastic doesn't support `.sql` files. There isn't an mature tree-sitter parser for SQL that I'm aware of.

**Comment by Wilfred** [comment]
See also #311.

**Comment by nh2** [comment]
I do not understand whether the commit that closed this issue should fix the following:

I inserted 2 lines into a Nix multi-line string, and `difftastic` shows the whole string as changed, making it difficult to see which lines are actually changed in `git diff`:

`difftastic`:

![image](https://user-images.githubusercontent.com/399535/197789801-23177cce-9b06-4e95-9b3b-a0d41f0bf6bb.png)


`delta`:

![image](https://user-images.githubusercontent.com/399535/197789433-c1958265-ad8f-469c-95b8-01b2449a7df5.png)

This is on `Difftastic 0.34.0`, which has commit https://github.com/Wilfred/difftastic/commit/a5de97a63cbda8ec5250dce6dc30d9c5bab6bd35 in -- should it look different?

**Comment by Wilfred** [comment]
@nh2 currently difftastic treats strings atomically, even when they're big multiline literals. See #178, it would be nice to do something better.

**Comment by nh2** [comment]
> I inserted 2 lines into a Nix multi-line string

@Wilfred Should https://github.com/Wilfred/difftastic/pull/409#issuecomment-1369976402 help with this?

E.g. would one need to write code similar to the one added in https://github.com/Wilfred/difftastic/commit/9133918dd40d7e55e605934994b87807728b201d ?

**Comment by Wilfred** [comment]
@nh2 I don't think sublanguages help here. In a generic string literal, there's no way for difftastic to know what the language in the string is.

Better handling of multiline comments/string is what will really help here I think.

**Comment by nh2** [comment]
@Wilfred It's shell script in ~95% of the cases. There are also some hints, e.g. the variable name that the string is assigned to.

Separate question though: VSCode auto-detects languages based on heuristics; if it looks like shell or Python, it guesses it. Such thing would certainly help here. Does difftastic have a such functionality one could turn on / do the libraries it uses provide such features?
