### ISSUE TITLE
Improve detection of extracted symbols

### ISSUE THREAD

**Issue by artuross** [Wilfred/difftastic#322]
Hey,

consider this example:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/8393226/180592895-fb6ad265-6677-4a30-8fbc-66a95cc9b7fd.png">

I think a more "valid" diff would be to show that `gui.render` has been wrapped by `helpers.OnScrollFunc` and that the next line is new.

Rendered diff shows as if `(helpers.OnScrollFunc(gui.render)).SetFocusFunc` was added.

I'm using version `0.31.0` on MacOS.

**Comment by Wilfred** [comment]
I agree. Could you try with 0.33 or later? That improved diffing logic.

Also, could you attach a copy of the file you're showing here, or share a link to it?

**Comment by artuross** [comment]
Closing, because I'm unable to check with that code whether it is working better now. Sorry for the delay 😅
