### ISSUE TITLE
Intra-line (word diff?) highlighting

### ISSUE THREAD

**Issue by vlsi** [Wilfred/difftastic#33]
I know the approach in difftastic is tree-based diff, so "intra-line" and "word-diff" might not be the right terms, however, it would be nice to see the modifications within the lines. For instance: function call added, or operand added, or variable name change.

For instance, see line 514 in https://github.com/Wilfred/difftastic/issues/32:

```diff
@@ -511,20 +511,21 @@ create or replace package body rte_data_capture is
               from table(vars.all_columns) c,
                    (select column_value data_field from table(vars.oldnew_columns)
                     union
-                    select column_value data_field from table(vars.change_tracker_columns)) cv
+                    select column_name data_field from table(vars.change_tracker_columns)) cv
```

`column_value` -> `column_name` is puzzling to spot in difftastic

**Comment by Wilfred** [comment]
When difftastic understands the syntax, it can do a good job. For files that it treats as text, I agree that word-level diffing is a reasonable approach :)

**Comment by vlsi** [comment]
Thanks for the quick fix.

The diff now is way better:
<img width="1410" alt="sample plsql diff" src="https://user-images.githubusercontent.com/213894/132296983-93da695a-b331-4f73-81aa-490cefa0f150.png">
