### ISSUE TITLE
difft detects GB18030-encoded files as binary with no apparent way to override

### ISSUE THREAD

**Issue by introp** [Wilfred/difftastic#330]
We get a lot of files from a vendor that are GB18030-encoded and difft believes them (sensibly so, I might add) to be binary.  Alas, there appears to be no way to specify the input encoding.  Right now I have to run `iconv -f GB18030 -t UTF-8` for every file, which is either quite slow (wrapper script that does it every time its needed) or quite clunky (convert the source files on disk and then deal with a mess of source code control deltas).  I'm hoping I'm either missing something or difftastic uses something like iconv_open under the hood and I could specify file encodings.

Thanks for any help or advice you might have!  :)

Expected behavior:
![image](https://user-images.githubusercontent.com/1137181/184017364-29bdfe9c-f66a-43f6-a95b-0f54025dbc26.png)

Observed behavior:
```sh
$ difft difft-binary-gb18030-left.c difft-binary-gb18030-right.c
difft-binary-gb18030-left.c --- binary
Binary contents changed.
```

Other info:
- Windows (x64 native or cygwin; both have the same behavior)
- difft --version: Difftastic 0.32.0

Test files in question (with .txt appended because github doesn't like uploading .c files):
[difft-binary-gb18030-left.c.txt](https://github.com/Wilfred/difftastic/files/9303943/difft-binary-gb18030-left.c.txt)
[difft-binary-gb18030-right.c.txt](https://github.com/Wilfred/difftastic/files/9303944/difft-binary-gb18030-right.c.txt)

**Comment by Wilfred** [comment]
I'm currently using https://lib.rs/crates/tree_magic_mini to recognise what a file is based on its bytes.

What does normal git do for you? Have you created a .gitattributes file?

**Comment by Wilfred** [comment]
https://git-scm.com/docs/git#_git_diffs suggests that encoding data isn't included in diff arguments at least.

**Comment by introp** [comment]
Good questions.  Because the vendor hasn't marked up their git repo correctly (git believes the files are UTF-8), the in-built git diff is of dubious usefulness because I have to do shenanigans like gitattributes+renormalizing or `git config --local core.pager "iconv -f GB18030 -t UTF-8 | less"` or setting `textconv` and then convincing git that applies.  That causes some encoding changes (with the same human-readable output) to show as a diff.  So I've been pulling down the repo, branching and running `iconv` on everything, repeating each time there's a vendor update.  Kind of a mess of a hassle.  I was hoping there was some way to convince `difft` to do some of that lifting for me.  There isn't, so that's cool, but I figured it couldn't hurt to ask.  It's still a great great tool and I'll just keep using it after manual file conversion.

Thank you for your help in thinking through this!  :)
