### ISSUE TITLE
Is detecting column width of the terminal on Windows not supported yet?

### ISSUE THREAD

**Issue by igrep** [Wilfred/difftastic#340]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

`difft` prints the diff within 80 columns no matter how wide my terminal is:

![image](https://user-images.githubusercontent.com/227057/186045518-35d8de7e-0aeb-460f-9e71-ea04df5d2706.png)

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

Changed [this file](https://github.com/Wilfred/difftastic/blob/f3420df1caaa7f4a79cba8e4ef79cb300f35442b/src/display/side_by_side.rs) as the screenshot above.

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

```
> difft --version
Difftastic 0.33.0
```

OS: Windows 10 Pro 21H2
Terminal: Windows Terminal 1.14.1962.0
Shell: PowerShell 7.2.6

**Comment by igrep** [comment]
Another question: I tried to fix this problem by myself, but I failed to run cargo build with an error:

```
> cargo build
   Compiling difftastic v0.34.0 (C:\t\difftastic)
error: failed to run custom build command for `difftastic v0.34.0 (C:\t\difftastic)`

Caused by:
  process didn't exit successfully: `C:\t\difftastic\target\debug\build\difftastic-c8d1297c37fbb275\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7
" "-Brepro" "-I" "vendor/tree-sitter-cpp-src" "-W4" "/std:c++14" "-FoC:\\t\\difftastic\\target\\debug\\build\\difftastic-193ac9cd16413c45\\out\\vendor/tree-sitter-cpp-src\\
scanner.o" "-c" "vendor/tree-sitter-cpp-src\\scanner.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

How are you build it on Windows?

**Comment by balta2ar** [comment]
I have the same issue on Linux Ubuntu 22.04 (zsh 5.8.1) when invoked like this:
```
echo 94c99c17d | GIT_EXTERNAL_DIFF='difft --color=always' xargs git show -m --ext-diff | less -R
```

**Comment by igrep** [comment]
@balta2ar If my knowledge is correct, in your case the stdout of `difft` is not a terminal. So automatic column size detection is not possible.

**Comment by balta2ar** [comment]
then I guess it would be useful to have it as an argument, then I could detect it manually before xargs and pass it to difft

**Comment by igrep** [comment]
@balta2ar Try ``difft --width `tput cols` ``, which is documented in `difft --help`
