### ISSUE TITLE
Would it be possible to view diffs for UTF-16 encoded files

### ISSUE THREAD

**Issue by brian6932** [Wilfred/difftastic#345]
(1) Not entirely a bug, but, when trying to view a diff of a UTF-16 encoded file, difftastic says, `Binary contents changed.`, it would be nice if there was some flag to change UTF modes or some UTF auto detection 🤷 

(3) Difftastic 0.33.0 on Windows 10

**Comment by brian6932** [comment]
@Wilfred Minor issue, this is working fine locally, however if I use difftastic as my git external diff in `~\.gitconfig`
```gitconfig
[diff]
	external = difft
```
and use `git diff commitHash^!`, It still says `Binary files differ`, this does not occur when just adding a UTF-16LE encoded file and then diffing HEAD though

**Comment by Wilfred** [comment]
@brian6932 if you share a git repository with this problem I'll take a look :)

**Comment by brian6932** [comment]
@Wilfred sure, this repo uses UTF16-LE encoded `.ini` config files:
https://github.com/RamonUnch/AltSnap
An example would be:
```
git diff b9b4caa8fcd1c74fcfb3a5b096398176e0ad6190^!
```

**Comment by Wilfred** [comment]
@brian6932 you're doing a normal git diff there!

```
$ git diff b9b4caa8fcd1c74fcfb3a5b096398176e0ad6190^! 
diff --cc AltSnap.ini
index 244b7b8,244b7b8..ea6d8c9
Binary files differ
```

This isn't a message from difftastic :)

**Comment by brian6932** [comment]
@Wilfred I have both `difftool` and `external` diff set to `difft`, does that not use `difft`? when I do:
```
git difftool b9b4caa8fcd1c74fcfb3a5b096398176e0ad6190^!
```
I get the same message.

Diff related parts of config for reference:
```gitconfig
[diff]
	external = difft
	tool = difftastic
[difftool]
	prompt = false
[difftool "difftastic"]
	cmd = difft "$LOCAL" "$REMOTE"
```
