### ISSUE TITLE
Auto detecting column width of the terminal don't work on git external diff tool

### ISSUE THREAD

**Issue by insight-21** [Wilfred/difftastic#346]
1. my git config
```bash
[diff]
        external = difft
```

2. use git diff
![image](https://user-images.githubusercontent.com/60787074/187410517-f1741e61-2e74-42e5-b880-4c0f581d4076.png)

3. It work if i use difft directly
![image](https://user-images.githubusercontent.com/60787074/187410431-32733286-1296-46d2-ba43-cb79dd38054a.png)

4. difft version
```bash
$ difft --version
Difftastic 0.34.0
```
OS: Windows 10 Pro 21H2
Terminal: Windows Terminal 1.13.11431.0

thanks for your reply!!!

**Comment by Wilfred** [comment]
Did it work in previous versions? I'm wondering if this is a regression.

**Comment by Wilfred** [comment]
Possibly related: #341.

**Comment by Wilfred** [comment]
This might be a regression, see discussion in cb900c3463caa3ec60f007bb3f8d3e88795b35e6.

**Comment by insight-21** [comment]
> Did it work in previous versions? I'm wondering if this is a regression.

the pre version have same issue
1. git diff
![image](https://user-images.githubusercontent.com/60787074/187598781-c04bad5a-4d81-476a-a071-fa6f038475eb.png)

2. difft
![image](https://user-images.githubusercontent.com/60787074/187598720-bc9d7f45-39a9-46da-9c3a-37ec8ba045ab.png)

**Comment by cspiegel** [comment]
> Did it work in previous versions? I'm wondering if this is a regression.

Yes, this worked in 0.33.0. I bisected the regression to f201b9e, which as you note, is the change in #341.

**Comment by chshersh** [comment]
I can confirm that `difft` version `v0.33.0` didn't have this issue for (when using `difft` as external diff with `git`):

**Version 0.34.0**

![difft now](https://user-images.githubusercontent.com/4276606/187969169-60b1670e-3f17-4a18-baba-10a06cdeb005.png)

**Version 0.33.0**

![difft before](https://user-images.githubusercontent.com/4276606/187969201-68349eb3-1999-4749-a3fd-bf912c786f0d.png)

Looking forward to the new release with the fix, I'm really enjoying Difftastic 🤗
