### ISSUE TITLE
Erroneous extra indent? 

### ISSUE THREAD

**Issue by x10an14** [Wilfred/difftastic#348]
Thanks for reporting a bug! Please include all of the following:

## A description of the issue. A screenshot is often helpful too.
Is this indent intended?

![2022-09-02T21:51:25,395480017+02:00](https://user-images.githubusercontent.com/710608/188226829-18a33a32-2338-495b-993f-5b650ac27434.png)

```
-> $ git diff -- home-manager/programs/terminal/direnv.nix
home-manager/programs/terminal/direnv.nix --- Nix
2    {
3      programs.direnv = {
4        enable = true;
5        enableBashIntegration = true;
   6     nix-direnv.enable = true;
   7   };
   8 }
```

## A copy of what you're diffing.
_If you're diffing files, include the before and after files._
_If you're using difftastic with a VCS repository (e.g. git), include the URL and commit hash._
Local file. Simple example:

```
-> $ cat home-manager/programs/terminal/direnv.nix
{config, ...}:
{
  programs.direnv = {
    enable = true;
    enableBashIntegration = true;
    nix-direnv.enable = true;
  };
}
-> $ bat home-manager/programs/terminal/direnv.nix
───────┬─────────────────────────────────────────────────────────
       │ File: home-manager/programs/terminal/direnv.nix
───────┼─────────────────────────────────────────────────────────
   1   │ {config, ...}:
   2   │ {
   3   │   programs.direnv = {
   4   │     enable = true;
   5   │     enableBashIntegration = true;
   6 + │     nix-direnv.enable = true;
   7   │   };
   8   │ }
───────┴─────────────────────────────────────────────────────────
```

## The version of difftastic you're using (see `difft --version`) and your operating system.
```
-> $ difft --version
Difftastic 0.32.0
-> $ echo "https://github.com/NixOS/nixpkgs/blob/$(jq -r '.nodes.nixpkgs.locked.rev' < flake.lock)/pkgs/tools/text/difftastic/default.nix"
https://github.com/NixOS/nixpkgs/blob/aaa1c973c8c189195e1b1a702d3b74dbcde91538/pkgs/tools/text/difftastic/default.nix
```

**Comment by Wilfred** [comment]
That looks correct to me, what were you expecting?

**Comment by x10an14** [comment]
> That looks correct to me, what were you expecting?

No indent in the line numbers/left margin, as shown in this picture from the Readme of this repo?

https://github.com/Wilfred/difftastic/blob/master/img/js.png

**Comment by x10an14** [comment]
Or timestamp ~0:30 from the demo gif located in the same repo (which actually shows inline diff).

**Comment by Wilfred** [comment]
The left column is the line numbers from the before file, and the right column is the line numbers from the after file. I think this particular example is clearer with the default display (but I would say that :) ).

![Screenshot from 2022-09-02 18-19-47](https://user-images.githubusercontent.com/70800/188250374-95d2cc6f-c5a4-422a-977d-0241d9341646.png)

Note that the closing brace is on line 8 in the after file, but line 7 in the before file.

**Comment by x10an14** [comment]
> The left column is the line numbers from the before file, and the right column is the line numbers from the after file. I think this particular example is clearer with the default display (but I would say that :) ).

I would agree, if both columns had continued all the way from the top to the bottom like in your screenshot and your examples in the Readme =)

That, I don't get in my example. I guess the pertinent question is if this is intended(the behavior I get where the leftmost column counts lines until diff, then stops - and where the rightmost column starts at diff, and continues all the way to EOF)?

**Comment by x10an14** [comment]
> @Wilfred> The left column is the line numbers from the before file, and the right column is the line numbers from the after file. I think this particular example is clearer with the default display (but I would say that :) ).
> 
> ![Screenshot from 2022-09-02 18-19-47](https://user-images.githubusercontent.com/70800/188250374-95d2cc6f-c5a4-422a-977d-0241d9341646.png)
> 
> Note that the closing brace is on line 8 in the after file, but line 7 in the before file.

I think I managed to figure out my confusion. [Your comment shows an inline diff](https://github.com/Wilfred/difftastic/issues/348#issuecomment-1236017763)  - however this output is not possible (with my example given in this thread) to reproduce when the `--display inline` flag is given to `difft`. 

That's what I found counter-intuitive, and tripped me up. I'm able to reproduce your output if I set `--display side-by-side` and the diff/file is small enough (or if I don't specify `--display` option).

> @Wilfred> That looks correct to me, what were you expecting?

I guess I can then understand why you find it so - we can close this thread if you'd like now, if you don't think this is something worth looking more into for ergonomic usage reasons.

**Comment by x10an14** [comment]
What I would have expected, would have been for the `--display inline` flag to trigger [the `ensure:contiguous()` code path](https://github.com/Wilfred/difftastic/blob/0.35.0/src/display/context.rs#L635), as [the inline diff shows in  your screenshot](https://github.com/Wilfred/difftastic/issues/348#issuecomment-1236017763).
