### ISSUE TITLE
No such file `/tmp/foo.cc`

### ISSUE THREAD

**Issue by jjbandit** [Wilfred/difftastic#355]
I just installed difftastic via `snap` on Ubuntu 18.04 and I'm getting what looks like a crash when I try to diff any files.

`difftastic -V` produces `Difftastic 0.35.0`

I set up difftastic as the global git diff tool as specified by the installation instructions:
`git config --global diff.external difftastic`

I've made spurious changes in both of these repositories to test:

`https://github.com/jjbandit/poof`
`https://github.com/oilshell/oil`

Both of which produce similar output:

```
poof $ git diff 
No such file: /tmp/giGe60_poof.cpp
fatal: external diff died, stopping at poof/poof.cpp
```

```
oil $ git diff                                                                         
No such file: /tmp/VnLgIJ_cheney_heap.cc
fatal: external diff died, stopping at mycpp/cheney_heap.cc
```

Diffing the previous commit results in a similar issue:

```
poof $ git log -p --ext-diff
commit 0721c25fe8450af0d7fbca97c0f8f1f3ef3a9c20 (HEAD -> master)
Author: Jesse Hughes <jesse.hughes.it@gmail.com>
Date:   Tue Sep 6 17:26:13 2022 -0600

    WIP

No such file: /tmp/sED70a_make.sh
No such file: /tmp/ybNa0a_make.sh
fatal: external diff died, stopping at make.sh
```

I get similar output for non-C codebases as well, so I'm lead to believe it's not the parser.  I also tried a random javascript codebase I had laying around:

`https://github.com/jjbandit/alphaterm`

Which also produced the same crash-y (?) behavior.

As far as I can tell the `/tmp` directory should be accessible for read/write to difftastic

```
$ ls -al /
... redacted ...
drwxrwxrwt  27 root      root      12288 Sep  7 07:14 tmp
... redacted ...
```

Happy to provide more info as necessary.  I really want to use this tool!

**Comment by alexmurray** [comment]
I maintain the [difftastic-snap](https://github.com/alexmurray/difftastic-snap) so it would probably worth moving this issue over to https://github.com/alexmurray/difftastic-snap/issues

But to explain what is going on here - snaps are confined and have their own private /tmp so when the unconfined git from the host system goes and creates a file in /tmp, when difftastic runs as a snap it cannot see that file as it runs with its own private /tmp. Instead you can workaround this by overriding `TMPDIR` when running git so that it uses a location which the snap can see (e.g. `~/tmp`):

```
TMPDIR=~/tmp GIT_EXTERNAL_DIFF="difftastic" git diff
```

**Comment by alexmurray** [comment]
@Wilfred FYI if you are interested in maintaining the snap of difftastic I would be happy to transfer ownership to you (but am also happy to keep maintaining it if you prefer).

**Comment by jjbandit** [comment]
Ah, got it, thanks for the explanation Alex.  I'll probably just download the tarball and throw it in `~/bin`

**Comment by Wilfred** [comment]
@alexmurray thanks for creating the snap and the offer! I'm trying to avoid getting involved in packaging, because there are too many different packaging tools for me to be able to handle all of them.
