### ISSUE TITLE
Enhancement request: highlight changes within moves

### ISSUE THREAD

**Issue by RMGiroux** [Wilfred/difftastic#362]
I have no idea if this is even possible, but it would be very nice to have.

Starting from difftastic's positions.rs file, apply the following patch:
```
☹  diff -p positions*rs
*** positions.rs        2022-09-08 14:23:56.000000000 -0400
--- positions2.rs       2022-09-08 14:24:16.000000000 -0400
***************
*** 1,6 ****
  //! Represents positions within a string.

- use crate::lines::LineNumber;

  /// A range within a single line of a string.
  #[derive(Debug, PartialEq, Clone, Copy, Eq, PartialOrd, Ord, Hash)]
--- 1,5 ----
*************** pub struct SingleLineSpan {
*** 10,12 ****
--- 9,13 ----
      pub start_col: u32,
      pub end_col: u32,
  }
+
+ use crate::lines::LineNumbers;
```

When doing `difft positions*.rs`, It shows that the use line was moved, but it does not highlight the added 's' on the moved line.

Is there any way that could be highlighted?  It's not so critical in a trivial sample like this, but when the moved block is 10's of lines and has just a few changes, they're impossible to spot.

**Comment by RMGiroux** [comment]
(Yes, the move and the changes should be separate commits - but that doesn't always happen)

**Comment by Wilfred** [comment]
Sadly I can't see any way of doing this within difftastic's model of changes I'm afraid. It just tracks additions and removals, difftastic doesn't have any notion of moves. Difftastic aims to minimise the number of additions/removals, so it considers the `use` changed rather than the `struct`.
