### ISSUE TITLE
Running in PowerShell / Command Prompt on Windows doesn't detect terminal width

### ISSUE THREAD

**Issue by hhartz** [Wilfred/difftastic#363]
Difftastic will not detect the terminal width, and therefore show a left-aligned, truncated view of the diff

Using [Difftastic 0.35.0](https://github.com/Wilfred/difftastic/releases/download/0.35.0/difft-x86_64-pc-windows-msvc.zip)

Reproducible using PowerShell or Command Prompt on Windows, on any git commit

**Comment by nzbart** [comment]
As a workaround, run the following to set the width prior to using difftastic:

```powershell
$env:DFT_WIDTH=$Host.UI.RawUI.WindowSize.Width
```

Note that you'll need to rerun this command if you resize your terminal window.

**Comment by nzbart** [comment]
To anyone triaging issues, this is probably a blocker for a lot of people adopting Difftastic on Windows.

**Comment by Lonami** [comment]
It also seems to fail in Git Bash. I tried looking in `term_size`, but indeed:

https://github.com/Wilfred/difftastic/blob/b9d44ae65f8d69ecd2c98b95bf2a5912e365d022/src/options.rs#L463 

That option is tried second though, so I guess the relevant issue for my problem is https://github.com/eminence/terminal-size/issues/25.

**Comment by Wilfred** [comment]
https://github.com/dandavison/delta/pull/1030/files is another approach that could fix this.

**Comment by Lonami** [comment]
Yeah, running either `stty` or `tput` should do the trick, but I'd prefer to dig into how those are querying the real size and doing it manually from Rust rather than relying on those `.exe` files existing (which always should for Git bash, but executing what could be an arbitrary command doesn't feel as clean)..

**Comment by Wilfred** [comment]
Please try 0.43, as crossterm (the new library) claims decent Windows support.

**Comment by Lonami** [comment]
Both Windows `cmd` and PowerShell seem to work, when running `difft` either standalone, or as the `difftool` configured for `git`! But unfortunately it doesn't work on Git Bash (MINGW64). But I guess this issue can be closed now.

**Comment by Wilfred** [comment]
Wonderful, that's major progress :)
