### ISSUE TITLE
Elm diff incorrectly reporting most comments changed

### ISSUE THREAD

**Issue by tankorsmash** [Wilfred/difftastic#364]
(1) A description of the issue:

Using difft as a diff tool seems to think all the comments in my file have changed, despite me not having changed any of them (see second screenshot for what actually changed). 

incorrect difft output (clipped since its several more pages of changes, dealing with unchanged comments):

![image](https://user-images.githubusercontent.com/1312390/189251889-b334c50d-906c-48ed-a81f-bfd183d5658b.png)

accurate git diff output (entirety):

![image](https://user-images.githubusercontent.com/1312390/189251812-0c12abf2-1d09-41cf-8177-e7316a9cda25.png)

(2) A copy of what you're diffing

[Original file](https://github.com/tankorsmash/lamdera_fooling/blob/ff4970eead91c3dedb93c077145c342aab297040~/src/PlayerDashboard.elm), and then new one with [the single section removed](https://github.com/tankorsmash/lamdera_fooling/blob/ff4970eead91c3dedb93c077145c342aab297040/src/PlayerDashboard.elm)

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

`Difftastic 0.35.0` Windows 10 Powershell through Windows Terminal

**Comment by Wilfred** [comment]
Hmm, this is an interesting case. Note that git is already warning you that newlines as CRLF are being replaced.

I think difftastic should ignore the newline at the end of comments, which should fix your issue. In principle multiline string literals would still be shown as changed though, and I don't think I can do much about that.

**Comment by tankorsmash** [comment]
I might be misunderstanding how lineendings work, but I don't believe I've changed any newlines for the comments; usually it's just the file's final line ending that gets changed.

 The [GitHub diff](https://github.com/tankorsmash/lamdera_fooling/commit/ff4970eead91c3dedb93c077145c342aab297040) only lists 7 deletions, it doesn't mention the line endings at all. My git's config is set to `autocrlf = input`.

**Comment by Wilfred** [comment]
Sure, I don't think you've changed the line endings, but the git is checking out the file with one type of line encodings, but the repository is storing the file with different line endings and difftastic is seeing one file of each type.

I think it would be good to fix comments in difftastic to not include the trailing newline, but ideally difftastic would detect the git autocrlf setting when this occurs.

**Comment by Wilfred** [comment]
Filed a bug upstream: https://github.com/elm-tooling/tree-sitter-elm/issues/133

**Comment by tankorsmash** [comment]
Thanks for taking the time to identity the root cause!
