### ISSUE TITLE
GUI version?

### ISSUE THREAD

**Issue by codec-abc** [Wilfred/difftastic#367]
Hi,

Cool project you have here!

I wonder if you thought about doing a GUI version of difftastic for those who prefer working with GUI over terminal.
Do you have something in mind for this?

**Comment by Wilfred** [comment]
I'm interested in providing HTML output #45 and making difftastic usable as a library #216, but I'm not interested in building a GUI application myself. I'd definitely mention any applications supporting difftastic in the readme though :)

**Comment by stellarpower** [comment]
Can it be included in an existing tool? It'd be cool (and reduce diplication!!) if, e.g., meld or kdiff could swap backends and just call into difftastic to perform the diff.

**Comment by stellarpower** [comment]
Communicating with an IDE such as VS Code might also be a good first step, with less overhead.

**Comment by tredondo** [comment]
> I'd definitely mention any applications supporting difftastic in the readme though :)

Have any GUIs integrated difftastic in the meantime? The [Zed effort](https://github.com/zed-industries/zed/issues/9721) looks abandoned :(
