### ISSUE TITLE
Fix examples in manual with a dark theme

### ISSUE THREAD

**Issue by Heistergand** [Wilfred/difftastic#374]
I'm just curious. This screenshot is from your documentation. Are those colors selected by any purpose? Or is it that I'm red-green-blind? I can hardly tell what's written light-grey on light-green and I cannot even guess whats written light-grey on light-orange. 

Please, make it barrier-free.

![image](https://user-images.githubusercontent.com/16416532/190633717-acbd5dea-813d-4a5c-9647-4f4992be211a.png)

**Comment by Wilfred** [comment]
Note that a light coloured theme in the manual is the default, and the colours currently assume that. I should either disable the dark mode or find a way to make these colours work well in both.
