### ISSUE TITLE
Inline hunks lose newlines with --color=never

### ISSUE THREAD

**Issue by jmattheis** [Wilfred/difftastic#383]
When using `--color=never` inline hunks will be printed without newlines. I'd expect difft to return the same newlines as the command without `--color=never`.

![image](https://user-images.githubusercontent.com/14895212/191322185-4f39ccbe-71b0-469d-9ade-eb860a7cce22.png)

<details>
  <summary>Image as text (click to expand)</summary>

```bash
$ difft --version
Difftastic 0.36.1
$ cat one
1
2
3
$ cat two
1
2
2.5
3
$ difft one two
two --- Text
1 1 1
2 2 2
. 3 2.5
3 4 3

$ difft --color=never one two
two --- Text
1 1 12 2 2. 3 2.53 4 3
```

</details>

---

Thanks for this awesome tool!

**Comment by Wilfred** [comment]
Probably broken in 3147eb8e6aa0b6609440dce80e46b977c2d88aa4, but see also 207151762142422545c6a8acb2adc39ba9e9343c.
