### ISSUE TITLE
Color line numbers differently

### ISSUE THREAD

**Issue by jmattheis** [Wilfred/difftastic#384]
Feel free to close this issue, as it's just a personal preference.

Currently, the line numbers have the same color as the normal text, this makes it a little difficult to read. Could we color the line numbers gray? Example:

![image](https://user-images.githubusercontent.com/14895212/191327617-980bc1c7-2e27-4daa-864d-09c27483373e.png)

**Comment by Wilfred** [comment]
I think this is a good idea: as you say, it's worth distinguishing line numbers from content.
