### ISSUE TITLE
Read one file from standard input

### ISSUE THREAD

**Issue by lcrilly** [Wilfred/difftastic#389]
I'm loving difftastic but my primary use case is to monitor config-drift for API-configured services. In short, I want to compare the running configuration of a JSON-configured service with the .json file (supposedly) used to configure it.

Ideally this would look like
```shell
curl -s localhost/config | difft my_conf.json
```

A single file might signify that the other is on stdin, but a `-` parameter is also conventional for such things.

**Comment by Wilfred** [comment]
Agreed that makes sense, added :)

**Comment by lcrilly** [comment]
That's fantastic, Wilfred - thanks! I'm using it already :)
