### ISSUE TITLE
A thought to use an approach from comby to improve performance

### ISSUE THREAD

**Issue by iilyak** [Wilfred/difftastic#390]
First of all fantastic tool. Great job!! 

In the readme I've noticed the caveat about performance and after reading the description of the approach used in the tool I've noticed some similarities with https://github.com/comby-tools/comby project.

Unfortunately comby is written in ocaml which makes borrowing ideas harder. Nevertheless maybe there is some venue to cross pollinate between these two projects.

**Comment by Wilfred** [comment]
Yeah, I'm familiar with Comby, and the first parser I wrote was based on Comby's design :)

tree-sitter parsers are a little more accurate though, and I don't believe Comby has many diff-related ideas that apply to me.

Thanks for the pointer though!

**Comment by Wilfred** [comment]
![comby_end](https://user-images.githubusercontent.com/70800/192081513-fb30b2e7-c155-4f44-89b8-6a8daea065b0.png)

Note the mismatched delimiters here -- I presume this is a word-based diff.
