### ISSUE TITLE
Add Erlang support

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#394]
See https://github.com/AbstractMachinesLab/tree-sitter-erlang

**Comment by illotum** [comment]
...and https://github.com/the-mikedavis/tree-sitter-erlang

**Comment by Wilfred** [comment]
https://github.com/WhatsApp/tree-sitter-erlang apparently has excellent language coverage too: https://twitter.com/alan_zimm/status/1585190286963113985
