### ISSUE TITLE
Only list files once, not for each hunk

### ISSUE THREAD

**Issue by blag** [Wilfred/difftastic#400]
First off, thank you for this project, it's wonderful!

Second, I apologize for the terrible image editing I did to illustrate my point here. They are terrible. Thank you for persevering through them.

That being said, I think there's a low-hanging fruit type of improvement that can be made to the display when displaying changes in multiple files.

The yellow color of the filename, and its large contrast with the black background, makes these changes all look like they happened in different files:

![Screen Shot 2022-10-04 at 2 58 20 PM](https://user-images.githubusercontent.com/597113/193940053-bef709f6-0842-4ed8-8d28-aaa0a5e37cc8.png)

The only thing that indicates that they are different hunks in the same files is the `X / Y` identifier after the filename. It is difficult to jump to the next file, because I have to visually read and cognitively compare the filenames and hunk numbers with the one above it as I go down the page. My eyes and brain have to do this motion:

![Screen Shot 2022-10-04 at 2 58 20 PM copy 2](https://user-images.githubusercontent.com/597113/193941395-f0076601-9649-4d58-88c0-dd2600bec78e.png)

I think it would be better to use color and contrast to differentiate hunks in different files, and less contrast to indicate hunks within the same file, like so:

![Screen Shot 2022-10-04 at 2 58 20 PM copy](https://user-images.githubusercontent.com/597113/193940378-7c208952-9777-4eb1-9769-0d1ed65a4a4e.png)

I didn't show it, but the next file would have the its filename in yellow, and the same grayish hunk identifier/s.

So really the only change that needs to be made is omitting displaying the filename for non-first hunks. I hope this is easy to do.

I think this would make it much easier to quickly scan through the output for different files, as the high-contrast yellow would differentiate changes between separate files a bit better than it does now. My eyes can jump from one yellow/high-contrast filename to the next instead:

![Screen Shot 2022-10-04 at 2 58 20 PM copy](https://user-images.githubusercontent.com/597113/193944419-95c32ba9-3230-4a17-84f9-e15df2032ef0.png)

(I forgot to edit in an empty line between the second filename and the preceding content, but let's just pretend it's there.)

There's a lot less to visually and cognitively process, so it should be easier and faster to quickly scan through.

Difftastic 0.27.0 on macOS 11.6.8 Big Sur (Intel), installed via Homebrew IIRC.

**Comment by john-rodewald** [comment]
I would be very interested in the same thing.

**Comment by Wilfred** [comment]
Thanks for the great bug report, this is a tricky area to get right :)

I prefer the current behaviour: it's easy to get lost in large diffs if you don't have the filename above every hunk. When using plain git-diff, I often find myself scrolling back up to see which file I'm looking at, then scrolling down to look at the changes that are interesting.

That said, I'm happy to add a setting for this. #434 is a really interesting idea: what if only the first occurrence of the filename was in colour? That'd make the 'on new file' boundary much clearer.

Would that suit your workflow, or would you rather have an option for only showing the filename on the first hunk?

**Comment by blag** [comment]
You make a good point about large diffs and scrolling around.

#434 is an excellent middle ground in my opinion. I would be happy with just that - no config option necessary. I also like the fact that that keeps the non-first filenames in bold, so it should also work for colorblind folks.

**Comment by Wilfred** [comment]
OK, I've merged #434.

Feel free to reopen if you hit a case that really needs to hide the filenames :)
