### ISSUE TITLE
alignment not correct when stdout is attached to a program

### ISSUE THREAD

**Issue by augustfengd** [Wilfred/difftastic#406]
Hello! For some reason the output's alignment is not correct (since 0.30.0) when difft's stdout is attached to a program.

Is this a bug? 

Thanks!

<img width="976" alt="image" src="https://user-images.githubusercontent.com/46177585/195749207-f5550f74-e555-4c74-959c-ce0c7436c8bd.png">

**Comment by Wilfred** [comment]
Could you attach or paste the exact files you're using?
