### ISSUE TITLE
Missing number in CSS diff

### ISSUE THREAD

**Issue by benwaffle** [Wilfred/difftastic#408]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

Top: difftastic, Middle: delta, Bottom: plain patch. Notice how the number `600` is entirely missing from difftastic's output.

<img width="761" alt="Screen Shot 2022-10-15 at 8 33 22 PM" src="https://user-images.githubusercontent.com/1713819/196002656-fc7c5516-3f0e-4cff-9d7c-0ca8c3cacc53.png">

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

```patch
diff --git a/styles/globals.css b/styles/globals.css
index 702029e..9580dc6 100644
--- a/styles/globals.css
+++ b/styles/globals.css
@@ -50,7 +50,7 @@ p.card-paragraph {
 }

 input[type='text'], input[type='number'], input[type='password'], textarea, select {
-  @apply rounded-md bg-gray-600;
+  @apply rounded-md bg-hss-dark-gray;
 }

 input[type='number'].no-spinners {
```

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.
```
❯ difft --version
Difftastic 0.37.0
```

**Comment by Wilfred** [comment]
OK, so what's happened here is that this syntax isn't valid vanilla CSS. There's an upstream parser request for it: https://github.com/tree-sitter/tree-sitter-css/issues/17

That said, the CSS parser is returning a nested error node and difftastic is doing a really bad job here. Error nodes need improvement anyway (see #267) but fixing this case is straightforward.
