### ISSUE TITLE
Document parser limitations

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#412]
The manual should describe which parsers have known limitations (e.g. Perl, Kotlin, YAML, Makefile)

**Comment by sesse** [comment]
There are also some weird things in the CSS parser, where quantities with units don't always go well. In “width: 50px”, there's a token for “50px” and a sub-token for “px”, but nothing for 50, which I've seen occasionally throw coloring off.

**Comment by Wilfred** [comment]
@sesse would you mind opening an issue for the CSS highlighting issue? If you have an example I can take a look.

**Comment by sesse** [comment]
Well, I noticed it only on a case that included my own PR #409, so I thought I couldn't really file a bug on something that hadn't been merged :-) But I'm fairly certain it's something that originates in the upstream parser, even if the only test case I've got includes my own code.

**Comment by Wilfred** [comment]
Now that difftastic has a parse error limit, that seems like a better solution than just writing a warning in the manual.
