### ISSUE TITLE
Nit: side-by-side sides should not have different widths

### ISSUE THREAD

**Issue by melonmouse** [Wilfred/difftastic#421]
This bug adresses a bit of a detail, but still I think it would improve difftastic. Difftastic is.. fantastic! Thanks for creating difftastic!!

Less nice (width is even):
![image](https://user-images.githubusercontent.com/73140350/200608615-171e668d-dcda-42fa-b9fc-a64dde7b4444.png)

Nice (width is odd):
![image](https://user-images.githubusercontent.com/73140350/200608792-055319d8-249c-440a-8eb9-1f0416312a71.png)

When the terminal size (or --width parameter) is even, the left and right diff get a different width in columns, which make them appear more different than they really are. To me, having both sides be the same width seems more important than saving space by showing one extra character in the right column.

One fix would be to internally reduce the output width by one if it is even (by default?). 

Difftastic 0.37.0

**Comment by Wilfred** [comment]
Great point, difftastic should definitely do this.
