### ISSUE TITLE
difft with rust-analyzer on VS Code seems to cause Out of memory

### ISSUE THREAD

**Issue by kyoheiu** [Wilfred/difftastic#429]
(1) A description of the issue. A screenshot is often helpful too.
```
difft --version
Difftastic 0.38.0
```

my `.gitconfig`:
```
[diff]
	external = difft
```

With this latest version, running rust-analyzer on VS Code seems to cause Out of memory on my machine.
It's hard to take a screenshot because linux kernel shuts down, but I took a photo by my smartphone (see below, process 13871, 13873). difft works too hard, doesn't it? (After a few seconds the monitor froze and kernel down)

![20221118_121909](https://user-images.githubusercontent.com/61998590/202610370-ff390a39-d1cb-4002-91f0-35ff7a75e8b3.jpg)

By removing `external` configuration in `.gitconfig` solves this issue. With the memory usage seen above, I think difft v0.38.0 does something wrong.

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

This happened during reading my own repository (develop branch): https://github.com/kyoheiu/felix

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

```
difft --version
Difftastic 0.38.0
```

```
rustc  ver: 1.65.0
rustup ver: 1.25.1
cargo  ver: 1.65.0
```

```
OS: Arch Linux x86_64
Kernel: 6.0.8-arch1-1
```

**Comment by kyoheiu** [comment]
Related? #373 
FYI, I still have the same problem even if I downgraded to 0.37.0, so maybe this is happening with VS Code's or other library's update.

**Comment by Wilfred** [comment]
difftastic can use a lot of memory, although I've tried to set limits. How much memory does your machine have?

Also, I note from your picture that there are multiple difftastic instances running, which might exacerbate the issue. If you want a quick workaround, I suggest substantially reducing `DFT_BYTE_LIMIT` and `DFT_GRAPH_LIMIT` from their default values.

Which commit on the felix repository were you on?

**Comment by Wilfred** [comment]
FWIW I think rust-analyzer isn't relevant here, it looks like the memory usage is all difftastic.

**Comment by kyoheiu** [comment]
> How much memory does your machine have?

16GB.

I tried to reproduce this situation, but now with difftastic v0.40.0, nothing unusual happens:smile: : Maybe the version-up solved something?

FYI, I suppose I was on this commit https://github.com/kyoheiu/felix/commit/15441a5a700efe56e11950499f66b776428bfd16.
