### ISSUE TITLE
In JS, brackets and curly-braces are reported as changed between for(x;y;z) and for(x of z) loops

### ISSUE THREAD

**Issue by gthb** [Wilfred/difftastic#430]
When I change a `for (let i = 0; i < arr.length; i++) { ... }` loop to a `for (const el of arr) { ... }` loop, difftastic shows the brackets and curly braces of the loop syntax as being changed.

![image](https://user-images.githubusercontent.com/153580/203021636-2a55e030-4299-487e-95fc-39add80c61d6.png)

Presumably this is because of different node types in the grammar, but I think for the user this is needless noise.

```before.js
const arr = [ 'a', 'b' ];

for (let i = 0; i < arr.length; i++) {
  const el = arr[i];
  console.log(el);
}
```

```after.js
const arr = [ 'a', 'b' ];

for (const el of arr) {
  console.log(el);
}
```

`difft --version` is 0.38.0 and my operating system is macOS Monterey, Version 12.6 (21G115)

**Comment by Wilfred** [comment]
This is a consequence of structural diffing I'm afraid. Difftastic has chosen to make `const el` and `arr` unchanged, but in the first file it's inside the braces, and on the second file it's outside. If the braces were unchanged, it'd have to say that `const el` was added and removed respectively.

**Comment by gthb** [comment]
Understood, thanks!

Still _some_ of this noise seems avoidable. I imagine a simple follow-up “pruning pass” after the structural diff, operating on the resulting diff spans to pluck away identical lexical tokens off the beginnings and ends of them. In this case it would prune away:

* the initial `(` token of the first diff span in line 3, `(let i = 0; i < arr.length; i++) {` → `(`
* the lone `}` token of the diff span in the final line (eliminating that span altogether)

(but it couldn't act on the `) {` because those tokens are removed in one diff span and added in another.)

From my (not very knowledgeable outsider's) perspective, that kind of pruning would clearly help in this case, and is feasible in general, if (as I'm supposing) the diff spans resuling from structural diffing are associated with spans of lexical tokens.

I guess what would make it infeasible is the cases which I'm not thinking of, in which this kind of pruning pass would hurt more than it helps, and which are not easy to tell apart from the good ones. I'd be curious to know what those are. :-)
