### ISSUE TITLE
difft@0.38.0 misclassifying JS files as binary. Sometimes. Depending on file size(?)

### ISSUE THREAD

**Issue by robertklep** [Wilfred/difftastic#433]
I recently upgraded to 0.38.0 from (I think) 0.35, using Homebrew on macOS Ventura 13.0 (M1 hardware), and it started to misclassify some of my Javascript files as binary.

I was able to narrow it down to a test with these two files:
(one.js)
```
if (! window.Home) {
  window.Home = new (class Home {
    constructor() {
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
      // random
    }
  })();
}
```
(two.js)
```
```
(yes, an empty file)

This yields the following result:
```
$ difft one.js two.js
two.js --- binary
Binary contents changed.
```

If I remove one of the `// random` lines, it works as expected.

**Comment by Wilfred** [comment]
Looks like the MIME type database is categorising the JS file as audio/x-mod. Difftastic should probably treat pure-ASCII files as text unconditionally.

**Comment by robertklep** [comment]
Ah, that would explain the issue 😊 JS files won't always be pure-ASCII though.
