### ISSUE TITLE
Upcoming change to tree-sitter-clojure

### ISSUE THREAD

**Issue by sogaiu** [Wilfred/difftastic#448]
I'm opening this issue to let the maintainers know that we're planning to merge a change to the tree-sitter-clojure master branch that might be of interest to this repository.

The change is here: sogaiu/tree-sitter-clojure#31

A brief overview of the changes follows.

`kwd_lit` and `sym_lit` will now contain up to 3 _new_ nodes:

```
(kwd_lit
  ns: (kwd_ns)
  delimiter: "/"
  name: (kwd_name))

(sym_lit
  ns: (sym_ns)
  delimiter: "/"
  name: (sym_name))
```

Only the `(kwd_name)` and `(sym_name)` are required.

`sym_lit` nodes can still contain metadata nodes (this is unchanged).

---

IIUC, difftastic currently uses a commit on the issue-21 branch of tree-sitter-clojure -- at least it seems so according to:

* https://github.com/Wilfred/difftastic/commit/bc4e22eee2f9606d2aeff940b2285eb9ba9d762a
* https://github.com/sogaiu/tree-sitter-clojure/commits/issue-21

So if that assessment is correct and the dependency doesn't change it seems our intended upcoming change shouldn't have any effect.

However, the change should also address https://github.com/sogaiu/tree-sitter-clojure/issues/21 which Wilfred reported to us earlier, so may be there would be some interest in using the updated code?

Please let us know if you decide to try the new code as well as if you encounter any issues.

Thanks!

P.S. Our current plan is to merge around 2023-01-05 which is in about 2 weeks time.

---

On a more general note...

Though at this time we don't anticipate many changes going forward, we're planning to post certain change-related announcements to [a pinned issue](https://github.com/sogaiu/tree-sitter-clojure/issues/33) ahead of merging such changes.

__Please have a look at the issue and consider subscribing :)__

**Comment by Wilfred** [comment]
Works nicely, thanks for letting me know :)
