### ISSUE TITLE
Panic with out of bound index

### ISSUE THREAD

**Issue by icp1994** [Wilfred/difftastic#452]
On Difftastic 0.41.0 with the relevant git config as follows:
```
[diff]
    external = difft --display inline --skip-unchanged --tab-width 4
```
#### Steps to repro
* mkdir difft-panic-demo
* cd difft-panic-demo
* git init .
* curl -fsSL https://github.com/riverwm/river/files/10370544/patch.txt -O
* git add patch.txt
* git commit -m "Initial commit"
* git log --patch --ext-diff

**Comment by Wilfred** [comment]
Thanks for the great report!
