### ISSUE TITLE
Rename vendor/ to vendored_parsers/

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#453]
Some packagers are assuming that vendor/ relates to `cargo vendor`, leading to confusion (they're unrelated).

**Comment by michel-slm** [comment]
Thanks!

Also this wreak havoc with tooling: if you run `cargo vendor` the `vendor` directory gets clobbered, so to get an archive suitable for offline builds some tweaks are required.

**Comment by Wilfred** [comment]
Needs fiddling with the Swift parser to get a successful build on a clean checkout.
