### ISSUE TITLE
what are the default options been used and if that is configurable?

### ISSUE THREAD

**Issue by shelper** [Wilfred/difftastic#468]
great tool, but when i run it i dont know what are the default options. 
there are ways to config it using envvars, but some of them do not have corresponding one. e.g., the option below, i dont know which is used when i run bare `difft`
```
 --color <WHEN>
            When to use color output.

            [possible values: always, auto, never]

```

I wonder if it makes sens to have somefile like `.difft` in home folder to configure these options, and also that could be an alternative to the envvars

**Comment by Wilfred** [comment]
Thanks for the feedback! I've added explicit defaults for both --display and --color, as they were missing.

Difftastic supports environment variables and command line flags, and I think that's sufficient at this point. I'm wary about adding more complexity.
