### ISSUE TITLE
internal error: entered unreachable code: Unchanged nodes should be both lists, or both atoms

### ISSUE THREAD

**Issue by sesse** [Wilfred/difftastic#469]
Difftastic as of git 9bdd1964b0fccf8e1bc8867b03b1b9713a06df04 (January 23rd, 2023). Files [a.cc](https://github.com/Wilfred/difftastic/files/10494804/a.txt), [b.cc](https://github.com/Wilfred/difftastic/files/10494805/b.txt) (they need to be renamed after download; GitHub doesn't support uploading .cc files, so I had to call them .txt)

Diffing the two attached files causes this error:

```
thread 'main' panicked at 'internal error: entered unreachable code: Unchanged nodes should be both lists, or both atoms', src/diff/changes.rs:54:14
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::panicking::unreachable_display
   3: difft::diff::changes::insert_deep_unchanged
   4: difft::diff::changes::insert_deep_unchanged
   5: difft::diff::sliders::fix_sliders
   6: difft::diff::sliders::fix_all_sliders
   7: difft::diff_file
   8: difft::main
```

The files were originally working C++ source files, but have been reduced; that's why they look funny.

**Comment by Wilfred** [comment]
Thanks for the super minimal repro :)
