### ISSUE TITLE
Insertion of a chunk of Java code erroneously shown as deletion and re-addition of the whole method

### ISSUE THREAD

**Issue by tomwhoiscontrary** [Wilfred/difftastic#471]
I have modified a Java file by inserting a one-line import at the top, and a chunk of code inside a method. Difftastic shows the whole body of the method being deleted and re-added with the change, and also shows the parameter lists of following methods being deleted and re-added unchanged.

One point of note is that the inserted chunk contains record definitions, which are a relatively new Java feature (Java 14, 17th March 2020). Even if this blows up parsing of the method, i'm surprised it affects the parameter lists of other methods.

The file before: [JSONUtilsTest.baseline.java.txt](https://github.com/Wilfred/difftastic/files/10512034/JSONUtilsTest.baseline.java.txt)

The file after: [JSONUtilsTest.changed.java.txt](https://github.com/Wilfred/difftastic/files/10512033/JSONUtilsTest.changed.java.txt)

Diff according to difft (contains escape codes for colour, use less -R or similar to view): [difft.txt](https://github.com/Wilfred/difftastic/files/10512056/difft.txt)

Diff according to diff -u (GNU diffutils 3.6): [diffu.txt](https://github.com/Wilfred/difftastic/files/10512055/diffu.txt)

* Difftastic 0.42.0
* rustc 1.67.0 (fc594f156 2023-01-24)
* Ubuntu 18.04.6 LTS

**Comment by Wilfred** [comment]
Thanks, I've filed this upstream: https://github.com/tree-sitter/tree-sitter-java/issues/136

Handling parse errors gracefully is a really difficult problem. Maybe difftastic should just fall back to textual diffs if there are any parse errors.

**Comment by Wilfred** [comment]
I've merged the latest upstream parser, and the test case now does the right thing.

![Screenshot from 2023-07-15 16-00-13](https://github.com/Wilfred/difftastic/assets/70800/0cfe9dee-8316-4f2d-acf6-9cf5c19dc5c9)
