### ISSUE TITLE
Makefile still reports no syntactic changes

### ISSUE THREAD

**Issue by NHOrus** [Wilfred/difftastic#476]
I think something is still broken in the difference engine.

With normal diff

```
diff --git a/Makefile b/Makefile
index 59f7e4e..0c57834 100644
--- a/Makefile
+++ b/Makefile
@@ -8,7 +8,7 @@ VERS=$(shell sed -n <NEWS '/^[0-9]/s/:.*//p' | head -1)
 .PHONY: check coverage
 
 CC?=gcc
-CCFLAGS+=-std=c99 -D_DEFAULT_SOURCE -DVERSION=\"$(VERS)\" -O2 -D_FORTIFY_SOURCE=2 -fstack-protector-all $(CFLAGS) -g
+CCFLAGS+=-std=c99 -D_DEFAULT_SOURCE -DVERSION=\"$(VERS)\" -O2 -Wall -Werror -D_FORTIFY_SOURCE=2 -fstack-protector-all $(CFLAGS) -g
 LIBS=$(shell pkg-config --libs libedit)
 INC+=$(shell pkg-config --cflags libedit)
```
With difftastic
```
Makefile --- Make
No syntactic changes.
```

[open-adventure](https://gitlab.com/esr/open-adventure.git) Makefile at 750cfe36d8a7d27f2200b5fd827a55cf6d8ae851

Difftastic 0.42.0 on Gentoo, installed from portage.

**Comment by Wilfred** [comment]
The Makefile parser can't quite cope with this file -- #472 fixes this :)

**Comment by Wilfred** [comment]
03985066f55dcd100644d2663dfc7770a0d197da also improves markdown parsing based on the sample.
