### ISSUE TITLE
CI only runs ignored tests

### ISSUE THREAD

**Issue by grawlinson** [Wilfred/difftastic#480]
As mentioned *after* issue #478 was closed, it looks like CI is only running ignored tests.

It looks like `cargo test -- --ignored` *only* runs ignored tests, according to CI output [here](https://github.com/Wilfred/difftastic/actions/runs/4093652298/jobs/7059244036#step:4:176).

Might have to run tests twice like so:

```sh
# run all tests (excluding ignored)
cargo test
# run ignored tests
cargo test -- --ignored
```

EDIT: Sorry for making another issue, some maintainers on GitHub have notifications turned off for closed issues, and I wasn't sure if you would see it.

**Comment by Wilfred** [comment]
Argh. Thanks, it was running the tests on mac and windows at least but I hadn't noticed that linux was only running one test.
