### ISSUE TITLE
"side-by-side-show-both" display variant is not properly documented.

### ISSUE THREAD

**Issue by vi** [Wilfred/difftastic#491]
Difftastic offers three display modes:

```
        --display <MODE>
            Display mode for showing results.

            [env: DFT_DISPLAY=]
            [default: side-by-side]
            [possible values: side-by-side, side-by-side-show-both, inline]
```

Difference between `side-by-side` and `inline` is obvious. But simple test (e.g. from the same sample files as in #490) did reveal differences between `side-by-side` and `side-by-side-show-both`, and I am not sure what does "show both" mean - both inline and side by side?

I expected [the book](https://difftastic.wilfred.me.uk/) to demonstrate those modes and `--help` text to shortly describe them.

```
$ difft --version
Difftastic 0.45.0
$ difft  --display=side-by-side  aa.h bb.h > x.txt
$ difft  --display=side-by-side-show-both  aa.h bb.h > y.txt
$ difft x.txt y.txt
y.txt --- Text
No changes.
```

**Comment by artuross** [comment]
I think the main difference is when new lines are added - with `side-by-side` those added lines are rendered on the left side; with `side-by-side-show-both` is rendered on the right side where it belongs.

**Comment by Wilfred** [comment]
Thanks, these options needed documenting.

I know the possible values are a little verbose, but changing them would be a breaking change. If people don't like the default, they can add `export DFT_DISPLAY=whatever` to your `.bashrc` once, so I don't think it's too bad :)
