### ISSUE TITLE
Difftastic does not ignore whitespace changes

### ISSUE THREAD

**Issue by skorokithakis** [Wilfred/difftastic#495]
I'm using Difftastic 0.45.0 and I get this output:

![image](https://user-images.githubusercontent.com/23648/224662770-e8fd9c9e-6c83-4d3a-9c17-aea6ae0697ea.png)

The only things that changed are whitespace, but the diff shows everything, is this correct? I would expect it to only show significant changes.

**Comment by Wilfred** [comment]
Note the header: it's treating your file as text and doing a textual diff. What language is your test file?

**Comment by skorokithakis** [comment]
Ahh, I missed that, sorry. It's C++, but even specifying `--language=Cpp` didn't change the diff, shouldn't it have?

**Comment by skorokithakis** [comment]
Somewhat counterintuitively, `--language` needs an extension, not a language (I missed this glancing at the help. Still, though:

```
19:41:56 $ GIT_EXTERNAL_DIFF="difft --language=cpp" git diff
code/src/main.ino --- Text (2 errors, exceeded DFT_PARSE_ERROR_LIMIT)
313     digitalWrite(ALARM_PIN, LOW);                                                                  313     digitalWrite(ALARM_PIN, LOW);
314                                                                                                    314 
315     snprintf(COMMAND_TOPIC, 128, "esplights/%08X/command", ESP.getChipId());                       315     snprintf(COMMAND_TOPIC, 128, "esplights/%08X/command", ESP.getChipId());
316     snprintf(GROUP_TOPIC, 128, "esplights/all/command");                                           316         snprintf(GROUP_TOPIC, 128, "esplights/all/command");
317     snprintf(STATE_TOPIC, 128, "esplights/%08X/state", ESP.getChipId());                           317     snprintf(STATE_TOPIC, 128, "esplights/%08X/state", ESP.getChipId());
318     snprintf(LOG_TOPIC, 128, "esplights/%08X/log", ESP.getChipId());                               318     snprintf(LOG_TOPIC, 128, "esplights/%08X/log", ESP.getChipId());
319     snprintf(HA_TEMP_TOPIC, 128, "homeassistant/sensor/%08X_temp/config", ESP.getChipId());        319     snprintf(HA_TEMP_TOPIC, 128, "homeassistant/sensor/%08X_temp/config", ESP.getChipId());
```

**Comment by skorokithakis** [comment]
I've created #496 to add the .ino extension as C++.

**Comment by Wilfred** [comment]
It sounds like this issue is resolved? I'm going to close this, but feel free to reopen if you can see anything I've missed.

**Comment by skorokithakis** [comment]
@Wilfred Yes, sorry, this is mostly resolved, though it would be good if there was some clearer documentation to say that the argument to `--language` is the extension, rather than a name.
