### ISSUE TITLE
Parse error on import('expr').Expr in .ts file

### ISSUE THREAD

**Issue by gthb** [Wilfred/difftastic#515]
Put this in a file `a.ts`:
```ts
type ExpressionNamerFn = (
  expr: import('expressions').Expr,
) => string;
```
Put something else in a file `b.ts`, for example:
```
type foo = 'bar' | 'baz';
```

Now `difft a.ts b.ts` and `difft b.ts a.ts` will fall back to text mode because of a parse error:
```
❯ difft a.ts b.ts
b.ts --- Text (1 error, exceeded DFT_PARSE_ERROR_LIMIT)
1 type ExpressionNamerFn = (                   1 type foo = 'bar' | 'baz';
2   expr: import('expressions').Expr,          . 
3 ) => string;                                 . 
4                                              2 
```

If I remove the `import(...).Expr` bit, this does not happen.

`difft --dump-syntax a.ts` looks reasonable and non-errory (I'm not very familiar with this syntax though) — here's the bit around the `import(...)`:

```
List id:9 content:8 {
    open_content: "",
    open_position: "1:6-6",
    children: [
        Atom id:10 content:5 {
            content: ":",
            position: "1:6-7",
        },
        Atom id:11 content:6 {
            content: "import('expressions').",
            position: "1:8-30",
        },
        Atom id:12 content:7 {
            content: "Expr",
            position: "1:30-34",
        },
    ],
    close_content: "",
    close_position: "1:34-34",
},
```

`difft --version` is Difftastic 0.46.0

OS is macOS 13.3.1 (a) (22E772610a)

**Comment by Wilfred** [comment]
Filed upstream: https://github.com/tree-sitter/tree-sitter-typescript/issues/246

I suggest you set DFT_PARSE_ERROR_LIMIT to a higher value, such as 5. The default value (0) is very conservative, but you generally get great results even if there are a few parse errors.
