### ISSUE TITLE
Use `DIFFT_LOG` instead of `RUST_LOG` environment variable

### ISSUE THREAD

**Issue by mamins1376** [Wilfred/difftastic#519]
When working on a project, it might be convenient to export `RUST_LOG=...` to avoid typing repetitive and long Cargo commands, But doing that would lead to having a really verbose output for `git diff`. Using a different name for that would resolve this.

```
$  difft --version
Difftastic 0.47.0
```

**Comment by Wilfred** [comment]
Thanks, that's a good idea.
