### ISSUE TITLE
[Feature Request] Better JSONL support (JSON != JSONL)

### ISSUE THREAD

**Issue by ganler** [Wilfred/difftastic#528]
Thanks for creating this great tool!

It seems `difftastic` supports `jsonl` by recognizing them as JSON files.

https://github.com/Wilfred/difftastic/blob/63a5eeaa984618baeb345df9dab6cc0df683202c/CHANGELOG.md?plain=1#L518

However JSONL != JSON as we need to split lines before doing comparison. Meanwhile when do `difft` over two `jsonl` files there seems to be parsing errors and the two files are recognized as text. I am curious if it is possible to support better JSONL support. Many thanks!

**Comment by Wilfred** [comment]
I've filed https://github.com/tree-sitter/tree-sitter-json/issues/37 FWIW.
