### ISSUE TITLE
[Question] Are language injections supported too for diffs?

### ISSUE THREAD

**Issue by FoamScience** [Wilfred/difftastic#529]
![2023-06-26_11-16](https://github.com/Wilfred/difftastic/assets/34474472/b3786c09-e0de-4782-a656-757b8ad93978)

In this small example, I'm trying to make `difftastic` use my parser, but I notice C++ injections are not diffed; is this an expected behavior at this point or did I miss something?

**Comment by Wilfred** [comment]
There is support for sublanguages, which is currently used for HTML and Make, e.g. https://github.com/Wilfred/difftastic/blob/63a5eeaa984618baeb345df9dab6cc0df683202c/src/parse/tree_sitter_parser.rs#L481
