### ISSUE TITLE
Read both files from stdin or text input 

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [Wilfred/difftastic#534]
A usecase that I often find myself in is wanting to compare two config files that live somewhere in a remote git location. I don't want to necessarily download those files and run `difft` on them. This would be some sort of extension over #389 Ideally I would like to do something like:

`dfft $(git show file1) $(git show file2)`

(the `git show filex` command does not exist, but you get the point).

Is this something that makes sense for this project?

P.D: Thanks so much for this, I love this tool

**Comment by Wilfred** [comment]
I'm open to suggestions, but I can't see any obvious way of doing this. stdin is a single item. I think you might be better off writing a helper that writes the files to a temporary file and returns that path, so you can pass it as an argument.

**Comment by Wilfred** [comment]
Closing this as I don't see any possibilities, but feel free to reopen if I've missed anything.

**Comment by maxdec** [comment]
This already works for me:

```difft <(helm get values my-release --revision 2) <(helm get values my-release --revision 1)```
