### ISSUE TITLE
[Feature request] Recognize unsignificant changes in order

### ISSUE THREAD

**Issue by fvictorio** [Wilfred/difftastic#539]
Hi, I don't know if this is something that's within the scope of difftastic, but I think it could be.

Sometimes IDEs or people change the order of something (normally sorting them lexicographically) in a way that has no semantic impact but that's hard to review. One example is a `package.json` file, where a change in the properties of the object can be safely ignored:

```diff
2,3d1
<   "name": "my-package",
<   "version": "1.0.0",
5c3,5
<   "main": "index.js"
---
>   "main": "index.js",
>   "name": "my-package",
>   "version": "1.0.0"
```

I understand that is is technically a significant syntax change, but I also think that difftastic could do something useful here. For example, these changes could still be highlighted but with a different color.

---

**Search terms**: sort sorted order properties

**Comment by 0xdevalias** [comment]
@fvictorio Have you looked into `git diff`'s `--color-moved` at all?

- https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt

Personally I tend to use the `zebra` mode of it. From my git aliases:

- https://github.com/0xdevalias/dotfiles/blob/a59d60e18b58069fe1d2c21dc5ef42a1c0afe797/git/gitconfig.symlink#L248-L259

```config
  # https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
  # https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-moved-wsltmodesgt
  # https://git-scm.com/docs/git-config#Documentation/git-config.txt-color
  # https://git-scm.com/docs/git-config#Documentation/git-config.txt-colordiffltslotgt
  diff-refactor = \
    -c color.diff.oldMoved='white dim' \
    -c color.diff.oldMovedAlternative='white dim' \
    -c color.diff.newMoved='white dim' \
    -c color.diff.newMovedAlternative='white dim' \
    -c color.diff.newMovedDimmed='white dim' \
    -c color.diff.newMovedAlternativeDimmed='white dim' \
    diff --ignore-blank-lines --color-moved=dimmed-zebra --color-moved-ws=ignore-all-space --minimal
```

**Comment by Wilfred** [comment]
Yeah, this is a syntactically significant change I'm afraid.

I have thought that it would be nice to highlight moves differently, but #508 is tracking that. Otherwise, I recommend sorting JSON with jq before diffing if you specifically want to compare unordered JSON.
