### ISSUE TITLE
Excessive memory usage from preallocating seen HashMap

### ISSUE THREAD

**Issue by yuzd** [Wilfred/difftastic#542]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.
![image](https://github.com/Wilfred/difftastic/assets/16083659/883fafe8-f076-400b-b8de-7dcfd0f9ab79)

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.
https://files.cnblogs.com/files/yudongdong/script_out.zip?t=1690611718&download=true

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.
0.49.0

**Comment by Wilfred** [comment]
Your URL doesn't work for me, I just get an error with 禁止访问. Could you attach the files to the task, or email me at me@wilfred.me.uk with the files?

**Comment by Wilfred** [comment]
Looks like the `size_hint` passed to Dijkstra needs to be capped a sensible value, or we try to allocate an absurdly large hashmap.
