### ISSUE TITLE
Display is too dim on white background terminals

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#55]

**Comment by Wilfred** [comment]
The best approach is probably to use bright colours on dark background, and detect if we're on a dark background:

* https://stackoverflow.com/questions/38287889/how-does-vim-guess-background-color-on-xterm/38287998#38287998
* https://lwn.net/Articles/664943/
* https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color

**Comment by JohnAZoidberg** [comment]
You don't necessarily have to detect it automatically. Having a switch to change the color scheme into a light one, would be good enough for me.
