### ISSUE TITLE
Code changes which do not change the AST are included in the diff

### ISSUE THREAD

**Issue by bradzacher** [Wilfred/difftastic#567]
```ts
// before
const x = [
  (1),
  2,
];

// after
const x = [
  1,
  2
]
```

### Expected:

Should be able to diff these two files and show no syntactic difference as they produce the same AST.

### Actual

![image](https://github.com/Wilfred/difftastic/assets/7462525/5ca750c3-9c6e-47bb-852e-134b2cc24dab)

### Extra

The two files have different CST's for sure, but the AST should be exactly the same:
- the parentheses do not change the AST of the program unless it impacts the precedence.
- the trailing comma after the final element is optional, and does not change the AST.
- the semicolon is (in this case) optional, and does not change the AST.

For context I'm comparing two transpilers to try to see how the output code differs and I'm struggling because the old transpiler omits the trailing comma and certain parentheses cases, but the new transpiler includes it.
I know these cases are just noise, but there's no way for me to exclude them from difftastic right now - which adds some difficulty to my analysis.

---

Side note that otherwise this has been an amazing tool for me. It's leaps and bounds ahead of raw text diffing and has made my life much easier!

**Comment by Wilfred** [comment]
Thanks for the feedback! It's always interesting to see how people use difftastic :)

I don't know of any language-agnostic way of deciding which parentheses aren't semantically meaningful. Semicolon insertion syntax is very JS specific.

I would like to handle the comma case better, see #419.

I don't think there's much else that I can offer I'm afraid. Difftastic is a simplistic syntactic tool. Have you considered running the files through prettier before diffing them?

**Comment by bradzacher** [comment]
You know I actually hadn't thought about prettier lol.
I passed the entire bundles through prettier, but not the transpiled files that make up the bundles.

We run the code through closure compiler after bundling which made comparing bundles a bit of a dead end:
- one slight difference in variable ordering / placement can vastly change the entire naming across the bundle
- the bundles are way too massive and thus difftastic can only do free-text diffing (tried bumping the limits but gave up after waiting about 5 mins for it to finish).

So yeah I'll see what happens after running each bundle through prettier - should cull a heap of noise!

**Comment by bradzacher** [comment]
> I don't know of any language-agnostic way of deciding which parentheses aren't semantically meaningful.

From my learnings working with ESLint and doing a bunch of work on ASTs and parsers - there's two different styles of sytnax trees.

- an AST which encodes the meaning of the code. It doesn't encode semicolon placement or parentheses.
- and a concrete syntax tree (CST) which encodes more information about the code - including things like parentheses placement.

From what I gather difftastic works on the CST (at least in the JS/TS case) which is why it can diff down to the individual, inconsequential token level.

There are trade-offs to stepping up to an AST - eg you can't diff at the token level as easily. Though I think for certain usecases of diffing it would be really useful to be able to do that.

**Comment by bradzacher** [comment]
Not sure if this is a separate report, but after formatting with prettier I ran into the following case:
![image](https://github.com/Wilfred/difftastic/assets/7462525/863484ba-a258-42ef-b1a2-df0be17b21b5)

The new transpiler dumped the object out WITH the newline, but the new transpiler dumped the object out WITHOUT it.
By design Prettier preserves the newline in object literals specifically.

Difftastic sees the added comma and shows it as a difference.

**Comment by Wilfred** [comment]
Beyond commas, I don't think there's much I can do here I'm afraid.
