### ISSUE TITLE
Add support for directory filtering

### ISSUE THREAD

**Issue by nimrodkor** [Wilfred/difftastic#568]
This is a really great tool!

I'm trying to use it outside of git, and apparently there's no easy way to filter out directories. There are some directories (`venv` for python, `node_modules` for js etc) which I definitely DO NOT want to diff. It's possible to implement this via reading a file (`.gitignore`?) or pass it in as an arg (or have it on by default). Are there any plans for this? I'm open to contributing if this sounds good and you need the extra hands 😄

**Comment by Wilfred** [comment]
This seems like a totally reasonable thing to add, I'm open to PRs here :)
