### ISSUE TITLE
`difft` does not understand json at the most basic level

### ISSUE THREAD

**Issue by magnusanderson-wk** [Wilfred/difftastic#577]
(1) A description of the issue. A screenshot is often helpful too.
Json objects are unordered. However,
<img width="777" alt="image" src="https://github.com/Wilfred/difftastic/assets/135166895/dfdbdf70-1370-4502-a5ee-f52e75bf852b">

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

a.json:
```
{
        "a": "a",
        "b": "b"
}
```
b.json:
```
{
	"b": "b",
	"a": "a"
}
```

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.
```
Difftastic 0.51.1
```
MacOS

**Comment by Wilfred** [comment]
Difftastic is a purely syntactic tool, so this is working as intended I'm afraid.

Some JSON implementations do care about definition order, and in general difftastic has no knowledge of when order doesn't matter. Similarly in Python, the sets `{1, 2}` and `{2, 1}` are different in source code but the same value.

You could normalise inputs with e.g. `jq --sort-keys` beforehand if you need order-insensitive diffing.
