### ISSUE TITLE
Feature Request: add support for Quarto (.qmd) files

### ISSUE THREAD

**Issue by natemcintosh** [Wilfred/difftastic#584]
Feel free to ignore and close this issue.

[Quarto](https://quarto.org/) files are very similar to markdown files, with YAML headers, and code blocks (R, python, julia, and Observable). 

Code blocks are denoted similarly to markdown, triple back-ticks. However, the name of the language is in curly brackets. See [an example here](https://quarto.org/docs/computations/r.html). 

I think ideally, difftastic support for quarto documents would use text diffing for everything except the code, and the relevant language for the code blocks.

**Comment by Wilfred** [comment]
Note that difftastic doesn't have markdown support yet, and support for nested languages is very limited (basically just HTML today).

**Comment by natemcintosh** [comment]
Gotcha. Thanks for explaining! Want me to close the issue?

**Comment by Wilfred** [comment]
Yeah, let's close this: it's not something I'm looking to support right now. If there's a mature tree-sitter parser for Quarto we can revisit this :)
