### ISSUE TITLE
"No such file: /tmp/xGR6oW_<file path>" when using with git

### ISSUE THREAD

**Issue by ittayd** [Wilfred/difftastic#592]
I installed difftastic via a snap on Ubuntu. Running directly from the CLI works. But using git difftool (configured according to the instructions) gives me two errors as the above.

**Comment by Wilfred** [comment]
Maybe the snap doesn't have access to `/tmp`? If you do `export DFT_LOG=info`, what does it show?

**Comment by ittayd** [comment]
```
 2023-11-17T09:09:49.919Z INFO  difft::options > CLI arguments: ["README.md", "/tmp/P2GI8O_README.md", "05c740702bf757d8d926cc05c8d57657c77dfcf6", "100644", "README.md", "0000000000000000000000000000000000000000", "100644"]
No such file: /tmp/P2GI8O_README.md
fatal: external diff died, stopping at README.md
```

**Comment by Wilfred** [comment]
Based on https://snapcraft.io/docs/security-sandboxing, it looks like snaps need to be given permission to access folders and presumably the snap binary doesn't have permission to access `/tmp`.

I don't maintain the snap package I'm afraid, could you file an issue with the packager?

**Comment by pyotr777** [comment]
No solution yet?

**Comment by e-vil-dev** [comment]
Snap [description](https://github.com/alexmurray/dif7ftastic-snap/blob/bf8d9c741dbfe76495eb6f87dc2982e7a85b8999/snapcraft.yaml#L19) has solution by switching to custom directory (`~/tmp`) for old file versions:

> To use the difftastic snap as an external diff tool with git, it should be
  invoked as:
      TMPDIR=~/tmp GIT_EXTERNAL_DIFF="difftastic" git diff


So just add into `.gitconfig`:
```
[difftool "difftastic"]
    cmd = "TMPDIR=~/tmp GIT_EXTERNAL_DIFF=\"difftastic\" git diff \"$REMOTE\""
```

**Comment by GabrielGCardoso** [comment]
I’m not exactly sure why the command above didn’t work for me, but the workaround using aliases worked for me

```
[alias]
	; difftastic aliases
	dlog = "!TMPDIR=$HOME/tmp git -c diff.external=difftastic log --ext-diff"
	dshow = "!TMPDIR=$HOME/tmp git -c diff.external=difftastic show --ext-diff"
	ddiff = "!TMPDIR=$HOME/tmp git -c diff.external=difftastic diff"
```
