### ISSUE TITLE
Panic diffing yaml

### ISSUE THREAD

**Issue by paholg** [Wilfred/difftastic#595]
Hello, I received a panic in difftastic when updating a Github Actions job.

Here is difftastic's output:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/display/side_by_side.rs:185:35
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: difft::display::side_by_side::print
   4: difft::print_diff_result
   5: difft::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have managed to produce the following minimal diff that causes the panic:

Before:
```yaml
foo: |
  ${{ BAR }}

```

After:
```yaml
foo: |
  bar

```
Note: The trailing newlines are important -- no panic without them.

```
$ difft --version
Difftastic 0.52.0
$ uname -a
Linux ubuntu 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Note: while I'm on Ubuntu, difftastic is installed via nix.

---

Thanks for this tool, by the way! I'm always sad on the rare occasions (like now) when I need to `git diff --no-ext-diff`.

**Comment by Wilfred** [comment]
Thanks, I can repro.
