### ISSUE TITLE
Does not run on SLES 12 b/c of glibc requirements

### ISSUE THREAD

**Issue by bmarwell** [Wilfred/difftastic#604]
Hi,

SLES 12 is still in support for 4 more years:
https://endoflife.date/sles

Can you make it run on SLES 12 by downgrading the build chain?

---

Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

Does not run on SLES 12:

```
user@host:~> ldd ~/bin/difft
$HOME/bin/difft: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by $HOME/bin/difft)
$HOME/bin/difft: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by $HOME/bin/difft)
$HOME/bin/difft: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by $HOME/bin/difft)
	linux-vdso.so.1 (0x00007ffe90dae000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fa728c6b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa728c4c000)
	libpthread.so.0 => /lib64/noelision/libpthread.so.0 (0x00007fa728c2e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa728b31000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa728b2d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa728987000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa72d1df000)
```

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

does not apply

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

https://github.com/Wilfred/difftastic/releases/tag/0.53.1

**Comment by Wilfred** [comment]
Can you install from source? I'm using the oldest version of Ubuntu in GitHub actions that is still supported.

**Comment by bmarwell** [comment]
I will try!

**Comment by bmarwell** [comment]
I tried using "cargo vendor" to do an offline installation, as I am in a restricted environment. However, I get this when I try `cargo build` on my SLES12 system:

```
$ cargo build --offline
error: failed to load source for dependency `tree_magic_mini`

Caused by:
  Unable to update https://github.com/Wilfred/tree_magic?branch=fix-panic-for-empty-strings#13dd6dda

Caused by:
  failed to update replaced source https://github.com/Wilfred/tree_magic?branch=fix-panic-for-empty-strings#13dd6dda

Caused by:
  failed to read root of directory source: $HOME/workspace/difftastic-0.53.1/vendor

Caused by:
  No such file or directory (os error 2)
```

As I am not a rust user, I need additional help.

Just FYI, `cargo install`:

```
$ cargo install --offline  --path $PWD
  Installing difftastic v0.53.1 ($HOME/workspace/difftastic-0.53.1)
error: failed to compile `difftastic v0.53.1 ($HOME/workspace/difftastic-0.53.1)`, intermediate artifacts can be found at `$HOME/workspace/difftastic-0.53.1/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to load source for dependency `tree_magic_mini`

Caused by:
  Unable to update https://github.com/Wilfred/tree_magic?branch=fix-panic-for-empty-strings

Caused by:
  the source https://github.com/Wilfred/tree_magic requires a lock file to be present first before it can be
  used against vendored source code

  remove the source replacement configuration, generate a lock file, and then
  restore the source replacement configuration to continue the build
```

**Comment by bmarwell** [comment]
Here's a build on 16.04. Will do 14.04 later after sorting out that no tls1.2 is available....
[difft-0.53.1-ubuntu16.04.tar.gz](https://github.com/Wilfred/difftastic/files/13692641/difft-0.53.1-ubuntu16.04.tar.gz)

**Comment by bmarwell** [comment]
Huh, that did not work:

```
[user@host:~/.local/apps/difftastic-0.53.1] $ ./bin/difft
./bin/difft: $HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./bin/difft)
./bin/difft: $HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./bin/difft)

[user@host:~/.local/apps/difftastic-0.53.1] $ ldd bin/difft
bin/difft: $HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bin/difft)
bin/difft: $HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bin/difft)
	linux-vdso.so.1 (0x00007ffdcece9000)
	libstdc++.so.6 => $HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6 (0x00007f32dc662000)
	libgcc_s.so.1 => $HOME/.local/apps/gcc-4.9.4/lib64/libgcc_s.so.1 (0x00007f32dc44b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f32dc42b000)
	libpthread.so.0 => /lib64/noelision/libpthread.so.0 (0x00007f32dc40d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f32dc310000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f32dc30b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f32dc166000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f32e0ed6000)
```

@Wilfred can you give me build instructions? I used relocate (so the build users does not appear), and that's it.

Not sure why `$HOME/.local/apps/gcc-4.9.4/lib64/libstdc++.so.6` got into it...

**Comment by bmarwell** [comment]
Actually, it works! I had a bad `LD_LIBRARY_PATH`.

BUILT on Ubuntu 16.04.

If you like, you can append them to the release. I'd love to see some download stats for them.

**Comment by Wilfred** [comment]
Glad you got it building! :)

I'm avoiding doing packaging for difftastic, as I'm not in a position to test lots of platforms and other people are doing a great job already. You might want to consider asking the upstream SUSE distro to package it?

**Comment by bmarwell** [comment]
> Glad you got it building! :)

Thanks :)

> You might want to consider asking the upstream SUSE distro to package it?

They will probably not accept it. It is EOL unless you are a premium customer, and they will probably only accept bug fixes unless there's a good reason.

I tried to talk the support into Upgrading a GnuPG version from 2012/2013 which was the last version which did not properly import ed255199 keys  (the next version a month later fixed a bug). They refused to backport it because it was not a security fix. So, SLES 12 is basically useless if you are trying to use a private GnuPG key more recent than 2020 or so... But thanks for the heads up :)
