### ISSUE TITLE
[Haskell] Strictness annotations (e.g. `!`) not recognized as syntactic changes

### ISSUE THREAD

**Issue by GeorgeFlerovsky** [Wilfred/difftastic#607]
When I run `difft X.hs Y.hs` with the files below, I expect it to detect the strictness annotations (`!`) that I've applied to the `a` and `b` fields of the `X` datatype in `Y.hs`. However, what I get instead is:

```sh
❯ difft X.hs Y.hs
Y.hs --- Haskell
No syntactic changes.
```

This is problematic because strictness annotations in Haskell are important syntax that can have implications for program performance and can even result in compilation errors when certain compiler plugins are used.

Example file `X.hs`:

```hs
module X where

data X = X
  { a :: Int
  , b :: String
  }
```

Example file `Y.hs`:

```hs
module X where

data X = X
 { a :: !Int
 , b :: !String
 }
```

Difftastic version:

```sh
❯ difft --version
Difftastic 0.53.1
```

**Comment by Wilfred** [comment]
I can work around this, but in general the Haskell parser doesn't keep all the tokens that would really help difftastic work as well as possible.

I've opened https://github.com/tree-sitter/tree-sitter-haskell/issues/107 for this, and https://github.com/tree-sitter/tree-sitter-haskell/issues/102 is kinda similar.
