### ISSUE TITLE
Version Control Merge Conflict Resolution

### ISSUE THREAD

**Issue by nordlow** [Wilfred/difftastic#608]
When will difftastic assist git (and vcs'es) in resolving merge conflicts? Will that require an entirely different tool such as `mergetastic`.

**Comment by Wilfred** [comment]
Merging is out of scope I'm afraid: https://github.com/Wilfred/difftastic#can-difftastic-do-merges

**Comment by rs545837** [comment]
For anyone still interested in this, I built [weave](https://github.com/ataraxy-labs/weave), a Git merge driver that uses tree-sitter (like difftastic) but for the merge side. It parses code into entities (functions, classes) and merges at that granularity. Two branches adding different functions to the same file? Clean merge, no conflict markers.

Different tool than difftastic (merge driver vs diff tool), but addresses exactly this request.
