### ISSUE TITLE
Is green highlighting missing, or am I misunderstanding?

### ISSUE THREAD

**Issue by tomjaguarpaw** [Wilfred/difftastic#609]
Thank you for this interesting tool. I'm having trouble interpreting the results and I'm not sure if it's because there's a bug or I'm misunderstanding something. Below is the output of `difft` on two small Haskell programs.

![screenshot1](https://github.com/Wilfred/difftastic/assets/1951567/43794df1-0010-41d5-b894-f21595a68e7c)

I had expected that `test1.hs` would consist of all grey and red numbered lines, and indeed it does. Correspondingly, I assumed that `test2.hs` would consist of all grey and green numbered lines, but it doesn't. I was expecting there to be an additional green numbered line as follows:

```
  2    print (if cond
```

Is it a bug that this line is missing, or am I supposed to interpret the diff in a different way, in order to know what the exact contents of `test2.hs` are? Thanks.

### Command line

```
difft /tmp/test1.hs /tmp/test2.hs --display=inline
```

### Version

Difftastic 0.53.1 (a67ad5b 2023-11-26)

### `test1.hs`

```.hs
example cond =
  print (if cond then 0 else 1,
         if cond then 2 else 3
        )
```

### `test2.hs`

```.hs
example cond =
  print (if cond
         then (0, 2)
         else (1, 3)
        )
```

**Comment by Wilfred** [comment]
Why would you expect line 2 to show as green? As far as I can see there are only removals on that line.

**Comment by tomjaguarpaw** [comment]
Hi Wilfred, thanks for your reply. Perhaps this is an [XY problem](https://en.wikipedia.org/wiki/XY_problem) so let me put it another way.

The standard diff tool on my system has the following property: from the content of `test1.hs` and the output of `diff test1.hs test2.hs` I can deduce the content of `test2.hs`. This seems to me to be the most essential property of a diff tool. Specifically, if `test1.hs` contains

```.hs
example cond =
  print (if cond then 0 else 1,
         if cond then 2 else 3
        )
```

and the output of `diff /tmp/test1.hs /tmp/test2.hs` is

```
2,3c2,4
<   print (if cond then 0 else 1,
<          if cond then 2 else 3
---
>   print (if cond
>          then (0, 2)
>          else (1, 3)
```

then I can deduce the content of `test2.hs` by replacing `test1.hs`'s lines 2 and 3 with the three lines in the second section of the `diff` output. However, I don't understand how the same deduction is possible using the output of `difft`. Perhaps I'm just unaware of the correct interpretation of the output format (or perhaps it's not supposed to be possible). Let's consider (for simplicity) the case without color, that is

```
difft --display=inline --color=never /tmp/test1.hs /tmp/test2.hs
```

The output is

```
/tmp/test2.hs --- Haskell
1    example cond =
2      print (if cond then 0 else 1,
3             if cond then 2 else 3
   3          then (0, 2)
   4          else (1, 3)
   5         )
```

How can I deduce the content of `test2.hs` knowing just the content of `test1.hs` and the output of `difft`? Put another way, if I were going to write the equivalent of `patch` for `difft`, what algorithm would I use to determine the effect of `difft`'s output on the original file? The difficulty here is that I don't know how I could determine that line 2 of `test2.hs` is

```
  print (if cond
```

**Comment by Wilfred** [comment]
Difftastic does not aim to provide a valid patch. There's a brief discussion in non-goals here: https://github.com/Wilfred/difftastic#non-goals

Difftastic works out the the relationship between the two files, and highlights the parts of the AST that don't match. That's why it considers the following JSON files the same:

```
[100, 200, 300]
```

```
[100,
 200,
 300]
```

It might be interesting to add a mode that shows a traditional patch with the AST diff elements highlighted. This would be tricky because some line-based patches are not syntactic changes (like the example above).

**Comment by tomjaguarpaw** [comment]
Sure, I don't actually want to apply the output of `difft` as a patch. I'm clearly explaining myself poorly. The fact that equivalent ASTs compare as equal is important information for me to take into account, thanks. I'll try again.

I'm asking whether, in principle, knowing the content of `test1.hs` and the output of `difft test1.hs test2.hs`, I should be able to deduce the content of `test2.hs`, modulo equivalent ASTs? That seems to me to be an essential property of a diffing tool, but it seems to me that `difft` doesn't have that property (example given above).

If it is a goal, does `difft` actually satisfy it? If not, then presumably it's a bug. If so, then can you explain how? I don't understand how to deduce the contents of `test2.hs` in the example above.

**Comment by Wilfred** [comment]
Yep, you should be able deduce the content of the second file modulo AST equivalence.

The inline display is harder to read, and I rarely use it. This is one of the inline display failure cases: when the line-based diff and AST diffs consider the first change to be in different lines, it's hard to render in a comprehensible way.

Here's the default display:

![Screenshot from 2023-12-30 11-26-49](https://github.com/Wilfred/difftastic/assets/70800/7395a84c-cbcc-4926-a3b1-b2b4687c7c3f)

From this, I can deduce that I can transform the first file into the second by opening a parenthesis before the 0, removing the `else 1` to get me up to the comma, and so on.

**Comment by tomjaguarpaw** [comment]
I see, thanks. For me an inline view is essential so I guess `difft` won't be a good fit for me. Still, I'm happy to have tried it out. Thanks for writing it!
