### ISSUE TITLE
Make it work with pager most

### ISSUE THREAD

**Issue by SteveLauC** [Wilfred/difftastic#610]
Thanks for this nice tool!

-----

Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

I use [`most`](https://en.wikipedia.org/wiki/Most_(Unix)#:~:text=most%20is%20a%20terminal%20pager,this%20sort%20are%20called%20pagers.) as my pager by [setting the `PAGER` environment variable](https://github.com/SteveLauC/dotfiles/blob/3c5417d5720cf49b45f37f3d3463454bd379fd8a/zsh/.zshrc#L49), so Git uses it as well, then when I use `difft` with `git diff`, the output will be weird:

![Screenshot from 2023-12-29 10-57-31](https://github.com/Wilfred/difftastic/assets/96880612/096a6b14-5d5f-4899-bc3d-aef4500fab00)

It seems that `most` does not understand the escape characters used by `difft`.

If I `unset PAGER`, then the output will be normal:

![Screenshot from 2023-12-29 10-57-48](https://github.com/Wilfred/difftastic/assets/96880612/f2c1ab48-7bde-4123-a2e3-46e323c396bb)

Is there any way to make these 2 tools work with each other?

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

Rust code, full diff can be seen in the above picutre.

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

```sh
$ difft -V
Difftastic 0.53.1

$ uname -a
Linux debian 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
```

**Comment by Wilfred** [comment]
It looks like `most` doesn't support the colour codes used by difftastic. You could disable colour with `export DFT_COLOR=never`, but I'd suggest switching pagers.

By the way, if you're just using `most` to make manpages look nicer, you can do this with less: https://github.com/Wilfred/dotfiles/blob/master/.zshrc#L128

**Comment by SteveLauC** [comment]
Thanks for the quick response!

Yeah, I think I will take your recommendation, thanks!
