### ISSUE TITLE
`git diff` fails when comparing files that differ only in file mode

### ISSUE THREAD

**Issue by kkrrz** [Wilfred/difftastic#615]
The steps to reproduce are as follows.

```sh
$ git config diff.external difft
$ touch foo bar
$ chmod 755 foo
$ git diff --no-ext-diff --no-index foo bar
diff --git foo bar
old mode 100755
new mode 100644
$ git diff --no-index foo bar
Segmentation fault: 11
```

```sh
$ difft --version
Difftastic 0.53.1
```

Tested on macOS 13.6.3

**Comment by Wilfred** [comment]
Thanks for the report. I think this might be a git issue: I can also replicate if the external diff is diff or cat.

**Comment by Wilfred** [comment]
I've reported upstream, the thread should soon appear in https://lore.kernel.org/git/ I think.

**Comment by Wilfred** [comment]
https://lore.kernel.org/git/CAFXAjY7XcL1APhLRXU8TO96z=f7957f2ieK56dHVsXUay55vpg@mail.gmail.com/T/#u

**Comment by Wilfred** [comment]
Fixed upstream, thanks for the report!
