### ISSUE TITLE
feature request: browser extension

### ISSUE THREAD

**Issue by ImLunaHey** [Wilfred/difftastic#616]
After switching `git diff` to use this by default I can't see myself ever going back.
The problem I have is PR diffs.

I would love if there was an extension that would replace the diff in PRs with this style.

Totally get if this isnt something you'd be interested in, feel free to close this issue if that's the case. 👍

**Comment by Wilfred** [comment]
I'm not interested in building this I'm afraid, difftastic already has enough functionality to keep me busy :)

**Comment by andersonaddo** [comment]
I made one!
https://andersonaddo.github.io/amadiff/

**Comment by singalen** [comment]
Too bad it broke over the year 8((( at least in Chrome.

**Comment by andersonaddo** [comment]
@singalen if you're talking about Amadiff, yeah something changed on Github's side and it broke.
Details here: https://github.com/andersonaddo/amadiff/issues/2
