### ISSUE TITLE
Git diff paths are confusing when using `git difftool` (but not `git diff`)

### ISSUE THREAD

**Issue by poliorcetics** [Wilfred/difftastic#620]
## Issue

```bash
cd /tmp/
cargo new --bin repro
cd repro
git add .
git commit -m "First commit"
echo 'fn main() { println!("Repro for difftastic"); dbg!(42); }' > src/main.rs
git difftool --tool difftastic  # See https://difftastic.wilfred.me.uk/git.html
```

This shows:

![Screenshot 2024-01-10 at 09 24 49](https://github.com/Wilfred/difftastic/assets/7951708/064963fb-f2db-4c9a-bbc9-26feea175aea)

Note the path: `main.rs` instead of `src/main.rs`. Using `GIT_EXTERNAL_DIFF=difft git diff` does not have this problem for some reason ?

## Solution

I replaced the `[difftool "difftastic"].cmd` with `echo "$LOCAL" "$REMOTE"` and it shows this: `/tmp/nix-shell.Pyzfqe/git-blob-OVxVxg/main.rs src/main.rs`

`/tmp/nix-shell.Pyzfqe` is `$TMPDIR` for me so really git is passing `LOCAL="$TMPDIR/git-blob-OVxVxg/main.rs"`.

So here is what I propose:

1. When two paths are given
2. And they're both files
3. And one of them starts with `$TMPDIR` and the other doesn't (when $TMPDIR is unset, `/tmp/` is used)
4. And the directory just under said TMPDIR starts with `git-blob-`
5. Then the path used in `difftastic` output should be the other path

I think this will work on both Linux and macOS. I don't know how git windows works

Note: the second path given to `difftool` is always from the root of the repo, we could make it relative to the current dir (when possible, falling back to the original path) to make it more intuitive, like a simple `git diff` works)

## Meta

- Difftastic: 0.54.0 (built with rustc 1.75.0)
- OS: macOS 14.1 (23B74)

**Comment by poliorcetics** [comment]
Workaround: using `cmd = difft --tab-width 4 "$BASE" "$LOCAL" "hash" "mode" "$REMOTE" "hash" "mode"` works well enough, though it is an hack based on how difftastic parses args and how "git diff" passes arguments

**Comment by Wilfred** [comment]
Thanks, I agree this is worth fixing and your heuristic sounds good.
