### ISSUE TITLE
Permission Denied while diffing sshfs mounted file

### ISSUE THREAD

**Issue by 4l1fe** [Wilfred/difftastic#621]
## Description

1. Mounted remote filesystem with `sshfs server.remote: /mnt/user/remote_user -o auto_unmount -o reconnect`
2. Trying to diff docker compose yaml files 
```
difftastic /home/user/docker-compose.local.yml /mnt/user/remote_user/docker-compose.yml
Permission denied when reading file: /mnt/user/remote_user/docker-compose.yml
```
3. Getting the error
```
Permission denied when reading file: /mnt/user/remote_user/docker-compose.yml
```

## Copy

Simply a bit different yaml files

## Versions
- 0.54.0 (35c1b4171 2024-01-05, built with rustc 1.63.0)
- Ubuntu 22.04.3, Linux 5.19.0-46-generic

**Comment by Wilfred** [comment]
I don't think this is a difftastic problem I'm afraid: the file needs to be readable for difftastic to be able to compare it.
