### ISSUE TITLE
Feature Request: CSV diffing that ignores useless information

### ISSUE THREAD

**Issue by johnpyp** [Wilfred/difftastic#648]
CSVs are notoriously inconsistent at giving you the same information. A few examples of things difftastic could help with that would be great:
- Don't care about header ordering - various csv writers will take in objects that are unordered, and non-deterministically choose a random order
- Ignore extraneous whitespace in places that it doesn't matter like extra newline (maybe some whitespace between fields that are quotes, I'm not sure)
- Inconsistent quotes where unnecessary (`"Asdf"` and `Asdf` should be considered equal)

**Comment by Wilfred** [comment]
Thanks for the suggestion. I think this is out of scope for difftastic: CSV is a somewhat ambiguous format, and difftastic does things like treating comment and strings separately that don't make sense in CSV.
