### ISSUE TITLE
How to disable syntax highlighting?

### ISSUE THREAD

**Issue by ralph-bergmann** [Wilfred/difftastic#655]
There is an option to [turn off syntax highlighting](https://github.com/Wilfred/difftastic/commit/12ef8f97da70bfa0ff18232ee1d0313de1906a75), but I have no clue how to use it :-(

I use `difftastic` to make `git diff` better. But sometimes, it has some bold text coming from syntax highlighting, which makes it hard to find the changes:
<img width="1680" alt="SCR-20240302-mudz" src="https://github.com/Wilfred/difftastic/assets/1191649/e50b5290-3840-4e53-92d4-126a2f64ba56">

How can I turn off syntax highlighting in my `~/.gitconfig`?

```
[diff]
   tool = difftastic
   external = difft

[difftool]
   prompt = false

[difftool "difftastic"]
   cmd = difft "$LOCAL" "$REMOTE"
```

**Comment by gerhardol** [comment]
https://github.com/Wilfred/difftastic/blob/master/src/options.rs

--syntax_highlight=off
or env var
DFT_SYNTAX_HIGHLIGHT=off

add to the command

**Comment by Wilfred** [comment]
Yep, the argument or environment variable. See also `difft --help` :)
