### ISSUE TITLE
Unchanged HTML reported as changed

### ISSUE THREAD

**Issue by Krinkle** [Wilfred/difftastic#696]
## Description

<img alt="Screenshot" src="https://github.com/Wilfred/difftastic/assets/156867/729c8101-8110-4331-b94a-ded4b1b0341f">

## Test case

Permalinks, the files are identical to the best of my knowledge:

* https://github.com/jquery/blog.jquery.com-theme/blob/6710984735eb980cc9845b17f98aa0db8eac09e6/jquery/search.php
* https://github.com/jquery/jquery-wp-content/blob/43bc52a23a7829701e599f8775061dfe1ba42028/themes/jquery/search.php

```
curl https://raw.githubusercontent.com/jquery/blog.jquery.com-theme/6710984735eb980cc9845b17f98aa0db8eac09e6/jquery/search.php > search-1.php
curl https://raw.githubusercontent.com/jquery/jquery-wp-content/43bc52a23a7829701e599f8775061dfe1ba42028/themes/jquery/search.php > search-2.php

difft search-1.php search-2.php
```

Compared to:
```
$ diff -w -u search-*.php
$
```

(zero exit status, no difference found.)

### Versions

```
$ difft --version
Difftastic 0.57.0 (built with rustc 1.77.1)

$ diff --version
diff (GNU diffutils) 3.7
```

**Comment by Delapouite** [comment]
These files differ in regards to their line endings (linux vs windows). You need to use the `--strip-cr` flag:

```sh
difft --strip-cr search-1.php search-2.php
```
