### ISSUE TITLE
No option to diff hidden files in directories

### ISSUE THREAD

**Issue by scott2000** [Wilfred/difftastic#697]
(1) When diffing two directories with hidden files, the hidden files (files starting with `.`) are excluded from the diff. This behavior makes sense by default, but I would like there to be an option to not exclude hidden files, since sometimes I want to see all changes I made. I would still like for files in `.gitignore` to be excluded from the diff, just not hidden files.

(2) There are two files `a/.hidden` and `b/.hidden` with different contents. I am trying to run `difft ./a ./b`.

(3) `Difftastic 0.56.1 (built with rustc 1.76.0)` on macOS 12.7.1

**Comment by Wilfred** [comment]
This should now work with difftastic 0.57, feel free to reopen if not.
