### ISSUE TITLE
[Question] Want to know the changes in the AST nodes of the old and new files?

### ISSUE THREAD

**Issue by yikengboy** [Wilfred/difftastic#720]
`
    public void foo() {
        System.out.println("foobar");
    }
`
`public void foo() {  }`

Just like the example above,  `foo` method should be a node of AST, I want to know which node of AST these code changes belong to. 
And I am a beginner in Rust. Can you provide some source code for reference?

**Comment by Wilfred** [comment]
You can play with `--dump-syntax` and `--dump-ts` to see the AST. I'm afraid difftastic isn't a great project for Rust beginners, but I'm sure you'll find some interesting projects elsewhere :)
