### ISSUE TITLE
pipe to PAGER lost syntax highlighting

### ISSUE THREAD

**Issue by laoshaw** [Wilfred/difftastic#743]
Thanks for reporting a bug! Please include all of the following:

(1) A description of the issue. A screenshot is often helpful too.

when I difft files and want to page it, then it loses all the syntax highlighting, tried less, bat -p, etc, none helped

in fact, can 'difft' support pager of its own

(2) A copy of what you're diffing. If you're diffing files, include the before and after files. If you're using difftastic with a VCS repository (e.g. git), include the URL and commit hash.

(3) The version of difftastic you're using (see `difft --version`) and your operating system.
Difftastic 0.59.0 (built with rustc 1.80.0)

**Comment by Wilfred** [comment]
Use `DFT_COLOR=always` if you want to enable colour even when output is a pipe, see `--help` for more details :)
