### ISSUE TITLE
Removals shown as red, but additions are not colored

### ISSUE THREAD

**Issue by osa1** [Wilfred/difftastic#745]
![difft_weird](https://github.com/user-attachments/assets/9f53107b-e77f-4372-9f33-3990d35a4352)

I'm using difft latest release (`Difftastic 0.59.0 (ffe27c5 2024-07-20, built with rustc 1.65.0)`).

As shown in the screenshot, difft renders removals as red, but additions are not colored.

As a result it's very difficult to parse what is addition. I have to compare with the left-hand side to see what's new in a line and what already existed.

I checked the user manual to see if this is configurable but I can't find anything.

I think ideally additions should be green, similar to standard command line diff tool.

**Comment by berrymot** [comment]
This is a problem with Solarized, your color theme: it annoyingly treats most non-"bright" colors as shades of gray

**Comment by osa1** [comment]
You are right, when I try with another color theme I see that additions are green. Thanks, closing.
