### ISSUE TITLE
Dependency graph is huge

### ISSUE THREAD

**Issue by catskul** [Wilfred/difftastic#786]
I was looking to get use of difftastic approved at my workplace and got rejected because analyzing the license and security implications was too difficult due to large number of dependencies.

According to github there 2,565 dependencies:

https://github.com/Wilfred/difftastic/network/dependencies

That seems unlikely. Any chance that this is a mistake, or that there's a single portion of this that is causing that explosion that could be called out to make this easier to analyze?

**Comment by Wilfred** [comment]
Closing as I don't think there's anything actionable from me, but happy to discuss further.

**Comment by catskul** [comment]
Thanks for the response. I think we're going to do a light fork. If we learn anything useful I'll share here.
