### ISSUE TITLE
diff for large jest snapshots (500k) takes 70 seconds

### ISSUE THREAD

**Issue by diefans** [Wilfred/difftastic#788]
I setup difftastic to work for `git diff`.

The diff for a large jest snapshot (around 500k for two files) takes more than 70 seconds, which is a torture for the impatient developer.

See https://jestjs.io/docs/snapshot-testing for details. Since the snapshot is basically one large javascript template string (\`) and I suppose difftastic is detecting the language here, my assumption is, that this involves much more CPU/time to calculate the diff. This is also the reason, why I have no hope that this will get fixed in any convenient way except detecting a jest snapshot and falling back to a simpler diff algorithm.

I cannot provide you with the specific contents of the snapshots, but may only tell you that it contains cdktf infrastructure stuff... (and yes... the road to hell is paved with good intentions)

```
❯ difft --version
Difftastic 0.61.0

Toolchain: 1.82.0
System:    linux x86_64
```

BTW: thanks for this tool!

**Comment by Wilfred** [comment]
Would you be willing to share the file with me privately, or redact the file and share it? My email is me@wilfred.me.uk.

Also, is difftastic doing a textual diff or a JS diff? Does it say `--- Text` or something else? How many lines and how many bytes are in the files?

**Comment by Wilfred** [comment]
Closing due to lack of response, happy to follow-up if you have details! :)
