### ISSUE TITLE
Bug in text differ

### ISSUE THREAD

**Issue by clonejo** [Wilfred/difftastic#90]
In this example, the added line "bar" is not visible in the diff. Instead, "baz" is printed twice.

```shell
$ printf "foo\n" >foo
$ printf "bar\nbaz\n" >bar
$ difft foo bar
bar --- 1/2 --- text
1 . foo

bar --- 2/2 --- text
1 2 baz
. 2 baz

$ difft --version
Difftastic 0.15.0
```

Also, shouldn't this be just one hunk?

**Comment by Wilfred** [comment]
Thanks for the report. I think this is a bug with alignment and display, and isn't specific to text diffing.

**Comment by Wilfred** [comment]
FWIW it's not too surprising that this case ended up with two hunks. The files have nothing at all in common, so difftastic struggles to work out if the first hunk (changing the left) and the second hunk (changing the right) are near enough to merge.

It's now a single hunk on master though.

**Comment by clonejo** [comment]
IMO either way would make sense.
