### ISSUE TITLE
Add `-R` for recursively comparsing directories

### ISSUE THREAD

**Issue by sdroege** [Wilfred/difftastic#98]
Similar to what `diff` can do, or at least GNU diff.

**Comment by Wilfred** [comment]
This should just work: difftastic compares directories if given directory arguments. It's necessary for mercurial support.

Does that suit your needs?

**Comment by sdroege** [comment]
That kind of works. It's just quite slow compared to `diff` on a bigger directory where only one file is different, and it prints "No changes" for every file that is the same, which is a bit noisy :)

**Comment by Wilfred** [comment]
OK, that's super helpful. Sounds like I need:

* Better usage docs
* Skip syntactic diffing on identical content to make this faster
* An option to hide unchanged files

**Comment by sdroege** [comment]
Sounds like a plan! Thanks for considering this :)
